/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp com.kylinsec.Kiran.SystemDaemon.Biometrics.xml -p Biometrics
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "biometrics-interface.h"

/*
 * Implementation of interface class BiometricsInterface
 */

BiometricsInterface::BiometricsInterface(const QDBusConnection &connection, QObject *parent) :
        QDBusAbstractInterface(staticInterfaceName(), staticInterfacePath(), staticInterfaceName(), connection, parent)
{

}

BiometricsInterface::~BiometricsInterface()
{

}

