variables:
  EXTRA_DNF_REPOS: |
                   [KylinSec_3.5.2_Customize_Kiran2.7]
                   name=Kiran2.7(standard_x86_64)
                   type=rpm-md
                   baseurl=http://build.kylinsec.com.cn:82/KylinSec:/3.5.2:/Customize:/Kiran2.7/standard_x86_64/
                   gpgcheck=1
                   gpgkey=http://build.kylinsec.com.cn:82/KylinSec:/3.5.2:/Customize:/Kiran2.7/standard_x86_64/repodata/repomd.xml.key
                   enabled=1
  CMAKE_OPTIONS: -DBUILD_EXAMPLE=true
  RPM_BUILD_REQUIRES: 'gcc-c++ cmake glib2-devel upower-devel zeromq-devel libnotify-devel pam-devel cryptopp-devel qt5-qtbase-devel qt5-qtx11extras-devel qt5-qtsvg-devel qt5-qtmultimedia-devel qt5-linguist kf5-networkmanager-qt-devel kiran-log-qt5-devel kiran-widgets-qt5-devel kiran-qt5-integration-devel kiran-qdbusxml2cpp kiran-cc-daemon-devel libqtxdg-devel kf5-kconfig-devel kiran-authentication-service-devel qt5-qtbase-static qt5-qtbase-private-devel kiran-desktop-libs-devel marco-devel'
  DEFAULT_IMAGE: kylinsec-3.5.2
include:
  - project: 'os/ks-devops'
    ref: main
    file: '/entrypoint/develop/cmake.yml'

