<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>AccountItemWidget</name>
    <message>
        <location filename="../../src/widgets/account-itemwidget.ui" line="14"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_account-itemwidget.h" line="83"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/widgets/account-itemwidget.ui" line="63"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_account-itemwidget.h" line="84"/>
        <source>Tom Hardy</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>AdvanceSettings</name>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="78"/>
        <source>Advance Settings</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="14"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="43"/>
        <source>Login shell</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="89"/>
        <source>Specify user id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="288"/>
        <source>confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="329"/>
        <source>cancel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="92"/>
        <location filename="../../src/pages/advance-settings.cpp" line="99"/>
        <source>Automatically generated by system</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="172"/>
        <source>Specify user home</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="123"/>
        <source>Please enter the correct path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="130"/>
        <source>Please enter specify user Id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="137"/>
        <source>Please enter the correct home directory</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CreateUserPage</name>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="101"/>
        <source>Login name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="147"/>
        <source>Account type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="64"/>
        <source>standard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="65"/>
        <source>administrator</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="14"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="190"/>
        <source>Password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="239"/>
        <source>Confirm password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="294"/>
        <source>Advance setting</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="389"/>
        <source>Confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="436"/>
        <source>Cancel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="83"/>
        <source>Please enter account name first</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="113"/>
        <source>Please enter your account name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="118"/>
        <source>Account already exists</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="129"/>
        <source>Please enter your password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="135"/>
        <source>Please enter the password again</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="141"/>
        <source>The password you enter must be the same as the former one</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="150"/>
        <location filename="../../src/pages/create-user-page.cpp" line="181"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="150"/>
        <source>Password encryption failed</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>HardWorker</name>
    <message>
        <location filename="../../src/hard-worker.cpp" line="40"/>
        <source>Create User failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="54"/>
        <source>password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="63"/>
        <source>home directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="72"/>
        <source>shell</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="80"/>
        <source>icon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="85"/>
        <source>Failed to set user attributes</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="109"/>
        <source> update password failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="130"/>
        <source>icon file</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="139"/>
        <source>account type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="148"/>
        <source>locked</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="155"/>
        <source>Failed to update user properties(%1)</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/hard-worker.cpp" line="170"/>
        <source>Failed to delete user</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KiranAccountManager</name>
    <message>
        <location filename="../../src/kiran-account-manager.cpp" line="85"/>
        <source>User Manager</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KiranAvatarEditor</name>
    <message>
        <location filename="../src/kiran-avatar-editor.cpp" line="26"/>
        <source>Avatar Editor</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/kiran-avatar-editor.cpp" line="72"/>
        <source>Confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/kiran-avatar-editor.cpp" line="90"/>
        <source>Cancel</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KiranTips</name>
    <message>
        <location filename="../../src/widgets/kiran-tips.ui" line="29"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>LineEditWithCheckIcon</name>
    <message>
        <location filename="../../src/widgets/lineedit-with-checkicon.ui" line="14"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SelectAvatarPage</name>
    <message>
        <location filename="../../src/pages/select-avatar-page.cpp" line="114"/>
        <source>Confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/select-avatar-page.cpp" line="127"/>
        <source>Return</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/select-avatar-page.cpp" line="140"/>
        <source>select greeter background</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/select-avatar-page.cpp" line="142"/>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>UserInfoPage</name>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="14"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="157"/>
        <source>Account</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="203"/>
        <source>Change password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="233"/>
        <source>User id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="292"/>
        <source>Account type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="354"/>
        <source>Account status</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="482"/>
        <source>Confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="523"/>
        <source>Delete</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="582"/>
        <source>Current password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="643"/>
        <source>New password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="692"/>
        <source>Enter the new password again</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="785"/>
        <source>Save</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="826"/>
        <source>Cancel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="90"/>
        <source>standard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="91"/>
        <source>administrator</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="230"/>
        <source>The directory and files under the user&apos;s home directory are deleted with the user.Are you sure you want to delete the user(%1)?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="232"/>
        <source>Warning</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="135"/>
        <source>Please enter the new user password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="142"/>
        <source>Please enter the password again</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="147"/>
        <source>The password you enter must be the same as the former one</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="156"/>
        <source>Please enter the current user password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="161"/>
        <source>The current password is incorrect</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="167"/>
        <source>The new password cannot be the same as the current password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="175"/>
        <location filename="../../src/pages/user-info-page.cpp" line="209"/>
        <location filename="../../src/pages/user-info-page.cpp" line="222"/>
        <location filename="../../src/pages/user-info-page.cpp" line="248"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="175"/>
        <source>Password encryption failed</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
