<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>AccountItemWidget</name>
    <message>
        <location filename="../../src/widgets/account-itemwidget.ui" line="14"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_account-itemwidget.h" line="83"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/widgets/account-itemwidget.ui" line="63"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_account-itemwidget.h" line="84"/>
        <source>Tom Hardy</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>AdvanceSettings</name>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="78"/>
        <source>Advance Settings</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="14"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="220"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="43"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="221"/>
        <source>Login shell</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="89"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="222"/>
        <source>Specify user id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="288"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="226"/>
        <source>confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="329"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="227"/>
        <source>cancel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="92"/>
        <location filename="../../src/pages/advance-settings.cpp" line="99"/>
        <source>Automatically generated by system</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.ui" line="172"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="224"/>
        <source>Specify user home</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="123"/>
        <source>Please enter the correct path</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="130"/>
        <source>Please enter specify user Id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/advance-settings.cpp" line="137"/>
        <source>Please enter the correct home directory</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>CreateUserPage</name>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="101"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="287"/>
        <source>Login name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="147"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="288"/>
        <source>Account type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="69"/>
        <source>standard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="70"/>
        <source>administrator</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="14"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="286"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="190"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="289"/>
        <source>Password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="239"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="290"/>
        <source>Confirm password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="294"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="291"/>
        <source>Advance setting</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="389"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="292"/>
        <source>Confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.ui" line="436"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="293"/>
        <source>Cancel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="88"/>
        <source>Please enter account name first</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="126"/>
        <source>Please enter your account name</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="131"/>
        <source>Account already exists</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="142"/>
        <source>Please enter your password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="148"/>
        <source>Please enter the password again</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="154"/>
        <source>The password you enter must be the same as the former one</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="163"/>
        <location filename="../../src/pages/create-user-page.cpp" line="184"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="163"/>
        <source>Password encryption failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="184"/>
        <source>Create User failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="201"/>
        <source>password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="211"/>
        <source>home directory</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="222"/>
        <source>shell</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="232"/>
        <source>icon</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="236"/>
        <source>Failed to set user attributes</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/create-user-page.cpp" line="247"/>
        <source>Warning</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KiranAccountManager</name>
    <message>
        <location filename="../../src/kiran-account-manager.cpp" line="86"/>
        <source>User Manager</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KiranAvatarEditor</name>
    <message>
        <location filename="../src/kiran-avatar-editor.cpp" line="26"/>
        <source>Avatar Editor</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/kiran-avatar-editor.cpp" line="72"/>
        <source>Confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../src/kiran-avatar-editor.cpp" line="90"/>
        <source>Cancel</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>KiranTips</name>
    <message>
        <location filename="../../src/widgets/kiran-tips.ui" line="29"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_kiran-tips.h" line="71"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>LineEditWithCheckIcon</name>
    <message>
        <location filename="../../src/widgets/lineedit-with-checkicon.ui" line="14"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_lineedit-with-checkicon.h" line="67"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>SelectAvatarPage</name>
    <message>
        <location filename="../../src/pages/select-avatar-page.cpp" line="114"/>
        <source>Confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/select-avatar-page.cpp" line="127"/>
        <source>Return</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/select-avatar-page.cpp" line="140"/>
        <source>select greeter background</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/select-avatar-page.cpp" line="142"/>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>UserInfoPage</name>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="14"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="488"/>
        <source>Form</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="157"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="489"/>
        <source>Account</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="203"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="490"/>
        <source>Change password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="233"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="491"/>
        <source>User id</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="292"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="492"/>
        <source>Account type</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="354"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="493"/>
        <source>Account status</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="482"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="495"/>
        <source>Confirm</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="523"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="496"/>
        <source>Delete</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="582"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="497"/>
        <source>Current password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="643"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="498"/>
        <source>New password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="692"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="499"/>
        <source>Enter the new password again</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="785"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="500"/>
        <source>Save</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.ui" line="826"/>
        <location filename="../../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="501"/>
        <source>Cancel</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="90"/>
        <source>standard</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="91"/>
        <source>administrator</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="106"/>
        <source>The directory and files under the user&apos;s home directory are deleted with the user.Are you sure you want to delete the user(%1)?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="108"/>
        <source>Warning</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="149"/>
        <source>Please enter the new user password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="156"/>
        <source>Please enter the password again</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="161"/>
        <source>The password you enter must be the same as the former one</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="170"/>
        <source>Please enter the current user password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="175"/>
        <source>The current password is incorrect</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="181"/>
        <source>The new password cannot be the same as the current password</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="189"/>
        <location filename="../../src/pages/user-info-page.cpp" line="197"/>
        <source>Error</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="189"/>
        <source>Password encryption failed</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/pages/user-info-page.cpp" line="197"/>
        <source>Failed to modify password</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
