//
// Created by lxh on 2020/10/27.
//

#ifndef KIRAN_ACCOUNT_MANAGER_EXIT_CODE_DEFINES_H
#define KIRAN_ACCOUNT_MANAGER_EXIT_CODE_DEFINES_H

#define EXIT_CODE_SUCCESS 0
#define EXIT_CODE_CANCEL 1
#define EXIT_CODE_BAD_ARG 2
#define EXIT_CODE_SAVE_FAILED 3
#define EXIT_CODE_MISSING_PARAMTER 4

#endif  //KIRAN_ACCOUNT_MANAGER_EXIT_CODE_DEFINES_H
