//
// Created by lxh on 2020/10/27.
//

#ifndef KIRAN_ACCOUNT_MANAGER_UI_DEFINES_H
#define KIRAN_ACCOUNT_MANAGER_UI_DEFINES_H

#define CUTTING_CIRCLE_RADIUS     150

#define IMAGE_SCALE_FACTOR_MAXIMUM 100
#define IMAGE_SCALE_FACTOR_MINIMUM (1/2.0)

#define SCALE_STEP_VALUE 0.05

#endif //KIRAN_ACCOUNT_MANAGER_UI_DEFINES_H
