<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>AccountItemWidget</name>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="14"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_account-itemwidget.h" line="83"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_account-itemwidget.h" line="83"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="63"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_account-itemwidget.h" line="84"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_account-itemwidget.h" line="84"/>
        <source>Tom Hardy</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="16"/>
        <source>Create new account</source>
        <translation>创建新账户</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="85"/>
        <source>disable</source>
        <translation>禁用</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="87"/>
        <source>enable</source>
        <translation>启用</translation>
    </message>
</context>
<context>
    <name>AdvanceSettings</name>
    <message>
        <location filename="../src/pages/advance-settings.cpp" line="78"/>
        <source>Advance Settings</source>
        <translation>高级设置</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.ui" line="14"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_advance-settings.h" line="220"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="220"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.ui" line="43"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_advance-settings.h" line="221"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="221"/>
        <source>Login shell</source>
        <translation>登录Shell</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.ui" line="89"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_advance-settings.h" line="222"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="222"/>
        <source>Specify user id</source>
        <translation>指定用户ID</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.ui" line="288"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_advance-settings.h" line="226"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="226"/>
        <source>confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.ui" line="329"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_advance-settings.h" line="227"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="227"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.cpp" line="92"/>
        <location filename="../src/pages/advance-settings.cpp" line="99"/>
        <source>Automatically generated by system</source>
        <translation>由系统自动生成</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.ui" line="172"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_advance-settings.h" line="224"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_advance-settings.h" line="224"/>
        <source>Specify user home</source>
        <translation>指定用户目录</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.cpp" line="123"/>
        <source>Please enter the correct path</source>
        <translation>请输入正确的路径</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.cpp" line="130"/>
        <source>Please enter specify user Id</source>
        <translation>请输入用户ID</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings.cpp" line="137"/>
        <source>Please enter the correct home directory</source>
        <translation>请输入正确的用户目录</translation>
    </message>
</context>
<context>
    <name>CreateUserPage</name>
    <message>
        <location filename="../src/pages/create-user-page.ui" line="101"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_create-user-page.h" line="287"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="287"/>
        <source>Login name</source>
        <translation>登录名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.ui" line="147"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_create-user-page.h" line="288"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="288"/>
        <source>Account type</source>
        <translation>账户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="64"/>
        <source>standard</source>
        <translation>普通用户</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="65"/>
        <source>administrator</source>
        <translation>管理员</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.ui" line="14"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_create-user-page.h" line="286"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="286"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.ui" line="190"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_create-user-page.h" line="289"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="289"/>
        <source>Password</source>
        <translation>账户密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.ui" line="239"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_create-user-page.h" line="290"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="290"/>
        <source>Confirm password</source>
        <translation>确认密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.ui" line="294"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_create-user-page.h" line="291"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="291"/>
        <source>Advance setting</source>
        <translation>高级设置</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.ui" line="389"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_create-user-page.h" line="292"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="292"/>
        <source>Confirm</source>
        <translation>创建</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.ui" line="436"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_create-user-page.h" line="293"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_create-user-page.h" line="293"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="82"/>
        <source>Please enter account name first</source>
        <translation>请先输入账户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="112"/>
        <source>Please enter your account name</source>
        <translation>请输入账户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="125"/>
        <source>Account cannot be a pure number</source>
        <translation>账户名不能全为数字</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="131"/>
        <source>Account already exists</source>
        <translation>账户名已存在</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="142"/>
        <source>Please enter your password</source>
        <translation>请输出密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="148"/>
        <source>Please enter the password again</source>
        <translation>请再次输入密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="154"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>两次密码不相同，请核对后，再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="163"/>
        <location filename="../src/pages/create-user-page.cpp" line="194"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page.cpp" line="163"/>
        <source>Password encryption failed</source>
        <translation>密码加密失败</translation>
    </message>
</context>
<context>
    <name>HardWorker</name>
    <message>
        <location filename="../src/hard-worker.cpp" line="32"/>
        <source>Create User failed</source>
        <translation>创建用户失败</translation>
    </message>
    <message>
        <source>password</source>
        <translation type="vanished">密码</translation>
    </message>
    <message>
        <source>home directory</source>
        <translation type="vanished">用户目录</translation>
    </message>
    <message>
        <source>shell</source>
        <translation type="vanished">shell</translation>
    </message>
    <message>
        <source>icon</source>
        <translation type="vanished">头像</translation>
    </message>
    <message>
        <source>Failed to set user attributes</source>
        <translation type="vanished">设置用户属性失败</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="120"/>
        <source> update password failed</source>
        <translation>更新密码失败</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="141"/>
        <source>icon file</source>
        <translation>头像</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="150"/>
        <source>account type</source>
        <translation>账户类型</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="159"/>
        <source>locked</source>
        <translation>启用状态</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="166"/>
        <source>Failed to update user properties(%1)</source>
        <translation>更新用户属性失败(%1)</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="182"/>
        <source>Failed to delete user</source>
        <translation>删除用户失败</translation>
    </message>
</context>
<context>
    <name>KiranAccountManager</name>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="86"/>
        <source>User Manager</source>
        <translation>账户管理工具</translation>
    </message>
</context>
<context>
    <name>KiranAvatarEditor</name>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="26"/>
        <source>Avatar Editor</source>
        <translation>头像编辑器</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="72"/>
        <source>Confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="90"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
</context>
<context>
    <name>KiranTips</name>
    <message>
        <location filename="../src/widgets/kiran-tips.ui" line="29"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_kiran-tips.h" line="71"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_kiran-tips.h" line="71"/>
        <source>Form</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>LineEditWithCheckIcon</name>
    <message>
        <location filename="../src/widgets/lineedit-with-checkicon.ui" line="14"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_lineedit-with-checkicon.h" line="67"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_lineedit-with-checkicon.h" line="67"/>
        <source>Form</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>SelectAvatarPage</name>
    <message>
        <location filename="../src/pages/select-avatar-page.cpp" line="114"/>
        <source>Confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page.cpp" line="127"/>
        <source>Return</source>
        <translation>返回</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page.cpp" line="140"/>
        <source>select picture</source>
        <translation>选择图片</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page.cpp" line="142"/>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation>图片文件(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</translation>
    </message>
</context>
<context>
    <name>UserInfoPage</name>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="14"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="489"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="489"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="157"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="490"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="490"/>
        <source>Account</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="203"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="491"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="491"/>
        <source>Change password</source>
        <translation>修改密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="233"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="492"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="492"/>
        <source>User id</source>
        <translation>用户ID</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="292"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="493"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="493"/>
        <source>Account type</source>
        <translation>账户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="354"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="494"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="494"/>
        <source>Account status</source>
        <translation>启用账户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="482"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="496"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="496"/>
        <source>Confirm</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="523"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="497"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="497"/>
        <source>Delete</source>
        <translation>删除用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="582"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="498"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="498"/>
        <source>Current password</source>
        <translation>当前密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="643"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="499"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="499"/>
        <source>New password</source>
        <translation>新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="692"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="500"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="500"/>
        <source>Enter the new password again</source>
        <translation>再次输入新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="785"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="501"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="501"/>
        <source>Save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.ui" line="826"/>
        <location filename="../build/kiran-account-manager_autogen/include/ui_user-info-page.h" line="502"/>
        <location filename="../cmake-build-debug/kiran-account-manager_autogen/include/ui_user-info-page.h" line="502"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="93"/>
        <source>standard</source>
        <translation>普通用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="94"/>
        <source>administrator</source>
        <translation>管理员</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="215"/>
        <source>Account information updated successfully</source>
        <translation>账户信息更新成功</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="231"/>
        <source>Password updated successfully</source>
        <translation>密码更新成功</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="236"/>
        <source>The directory and files under the user&apos;s home directory are deleted with the user.Are you sure you want to delete the user(%1)?</source>
        <translation>用户目录下的目录和文件会随用户一起删除，确定要删除%1用户吗？</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="238"/>
        <source>Warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="138"/>
        <source>Please enter the new user password</source>
        <translation>请输入新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="145"/>
        <source>Please enter the password again</source>
        <translation>请再次输入密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="150"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>两次密码不相同，请核对后，再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="159"/>
        <source>Please enter the current user password</source>
        <translation>请输入当前密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="164"/>
        <source>The current password is incorrect</source>
        <translation>当前密码错误，请再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="170"/>
        <source>The new password cannot be the same as the current password</source>
        <translation>新密码不能和旧密码相同，请重新输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="178"/>
        <location filename="../src/pages/user-info-page.cpp" line="212"/>
        <location filename="../src/pages/user-info-page.cpp" line="227"/>
        <location filename="../src/pages/user-info-page.cpp" line="254"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page.cpp" line="178"/>
        <source>Password encryption failed</source>
        <translation>密码加密失败</translation>
    </message>
</context>
</TS>
