<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="zh_CN">
<context>
    <name>AccountItemWidget</name>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_account-itemwidget.h" line="83"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_account-itemwidget.h" line="83"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="63"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_account-itemwidget.h" line="84"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_account-itemwidget.h" line="84"/>
        <source>Tom Hardy</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="36"/>
        <source>Create new user</source>
        <translation>创建新用户</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="108"/>
        <source>disable</source>
        <translation>禁用</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="112"/>
        <source>enable</source>
        <translation>启用</translation>
    </message>
</context>
<context>
    <name>AdvanceSettings</name>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="112"/>
        <source>Advance Settings</source>
        <translation>高级设置</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="203"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="203"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="43"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="204"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="204"/>
        <source>Login shell</source>
        <translation>登录Shell</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="89"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="205"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="205"/>
        <source>Specify user id</source>
        <translation>指定用户ID</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="262"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="207"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="207"/>
        <source>confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="303"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="208"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="208"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="129"/>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="139"/>
        <source>Automatically generated by system</source>
        <translation>由系统自动生成</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="159"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="206"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="206"/>
        <source>Specify user home</source>
        <translation>指定用户目录</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="171"/>
        <source>Please enter the correct path</source>
        <translation>请输入正确的路径</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="179"/>
        <source>Please enter specify user Id</source>
        <translation>请输入用户ID</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="187"/>
        <source>Please enter the correct home directory</source>
        <translation>请输入正确的用户目录</translation>
    </message>
</context>
<context>
    <name>AuthManagerPage</name>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="179"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="179"/>
        <source>AuthManagerPage</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="47"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="180"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="180"/>
        <source>Fingerprint Authentication</source>
        <translation>指纹认证</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="91"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="181"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="181"/>
        <source>Face Authentication</source>
        <translation>人脸认证</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="134"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="182"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="182"/>
        <source>Password Authentication</source>
        <translation>密码认证</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="208"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="183"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="183"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="249"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="184"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="184"/>
        <source>return</source>
        <translation>返回</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="162"/>
        <source>add fingerprint</source>
        <translation>录入指纹数据</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="175"/>
        <source>add face</source>
        <translation>录入人脸数据</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="192"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="342"/>
        <source>error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="193"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="343"/>
        <source>please ensure that at least one authentication option exists</source>
        <translation>请确保至少一个认证选项打开</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="506"/>
        <source>fingerprint_</source>
        <translation>指纹_</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="506"/>
        <source>face_</source>
        <translation>人脸_</translation>
    </message>
</context>
<context>
    <name>BiometricItem</name>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="77"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="77"/>
        <source>BiometricItem</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="35"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="78"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="78"/>
        <source>text</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="73"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="79"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="79"/>
        <source>add</source>
        <translation>添加</translation>
    </message>
</context>
<context>
    <name>CreateUserPage</name>
    <message>
        <source>Account type</source>
        <translation>账户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="80"/>
        <source>standard</source>
        <translation>普通用户</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="81"/>
        <source>administrator</source>
        <translation>管理员</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="286"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="286"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="101"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="287"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="287"/>
        <source>User name</source>
        <translation>用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="147"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="288"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="288"/>
        <source>User type</source>
        <translation>用户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="190"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="289"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="289"/>
        <source>Password</source>
        <translation>用户密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="239"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="290"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="290"/>
        <source>Confirm password</source>
        <translation>确认密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="294"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="291"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="291"/>
        <source>Advance setting</source>
        <translation>高级设置</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="389"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="292"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="292"/>
        <source>Confirm</source>
        <translation>创建</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="436"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="293"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="293"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <source>Please enter account name first</source>
        <translation>请先输入账户名</translation>
    </message>
    <message>
        <source>Please enter your account name</source>
        <translation>请输入账户名</translation>
    </message>
    <message>
        <source>Account cannot be a pure number</source>
        <translation>账户名不能全为数字</translation>
    </message>
    <message>
        <source>Account already exists</source>
        <translation>账户名已存在</translation>
    </message>
    <message>
        <source>Please enter your userName name</source>
        <translation>请输入用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="99"/>
        <source>Please enter user name first</source>
        <translation>请输入用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="133"/>
        <source>Please enter your user name</source>
        <translation>请输入用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="149"/>
        <source>user name cannot be a pure number</source>
        <translation>用户名不能全为数字</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="156"/>
        <source>user name already exists</source>
        <translation>用户名已存在</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="168"/>
        <source>Please enter your password</source>
        <translation>请输出密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="175"/>
        <source>Please enter the password again</source>
        <translation>请再次输入密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="182"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>两次密码不相同，请核对后，再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="192"/>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="227"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="192"/>
        <source>Password encryption failed</source>
        <translation>密码加密失败</translation>
    </message>
</context>
<context>
    <name>FaceEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_face-enroll-dialog.h" line="122"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_face-enroll-dialog.h" line="122"/>
        <source>FaceEnrollDialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="63"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_face-enroll-dialog.h" line="123"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_face-enroll-dialog.h" line="123"/>
        <source>balabalalbala...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="121"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_face-enroll-dialog.h" line="124"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_face-enroll-dialog.h" line="124"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="159"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_face-enroll-dialog.h" line="125"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_face-enroll-dialog.h" line="125"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="69"/>
        <source>initializing face collection environment...</source>
        <translation>正在初始化人脸采集环境，请稍后</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="119"/>
        <source>failed to initialize face collection environment!</source>
        <translation>初始化人脸采集环境失败!</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="130"/>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="141"/>
        <source>Failed to start collection</source>
        <translation>开始采集失败</translation>
    </message>
</context>
<context>
    <name>FaceInputDialog</name>
    <message>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <source>initializing face collection environment...</source>
        <translation>正在初始化人脸采集环境，请稍后</translation>
    </message>
    <message>
        <source>failed to initialize face collection environment!</source>
        <translation>初始化人脸采集环境失败!</translation>
    </message>
    <message>
        <source>Failed to start collection</source>
        <translation>开始采集失败</translation>
    </message>
</context>
<context>
    <name>FingerprintEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_fingerprint-enroll-dialog.h" line="131"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_fingerprint-enroll-dialog.h" line="131"/>
        <source>FingerprintEnrollDialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="70"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_fingerprint-enroll-dialog.h" line="132"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_fingerprint-enroll-dialog.h" line="132"/>
        <source>balabalalbala...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="131"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_fingerprint-enroll-dialog.h" line="133"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_fingerprint-enroll-dialog.h" line="133"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="169"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_fingerprint-enroll-dialog.h" line="134"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_fingerprint-enroll-dialog.h" line="134"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="49"/>
        <source>Finger Enroll</source>
        <translation>指纹录入</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="127"/>
        <source>This fingerprint is bound to the user(%1)</source>
        <translation>该指纹已绑定用户(%1)</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="129"/>
        <source>Info</source>
        <translation>提示</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="154"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
</context>
<context>
    <name>FingerprintInputDialog</name>
    <message>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <source>Finger Enroll</source>
        <translation>指纹录入</translation>
    </message>
    <message>
        <source>Error</source>
        <translation>错误</translation>
    </message>
</context>
<context>
    <name>FingerprintInputWorker</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-worker.cpp" line="78"/>
        <source>initializing fingerprint collection environment...</source>
        <translation>正在初始化指纹采集环境，请稍等</translation>
    </message>
</context>
<context>
    <name>HardWorker</name>
    <message>
        <location filename="../src/hard-worker.cpp" line="46"/>
        <source>Create User failed</source>
        <translation>创建用户失败</translation>
    </message>
    <message>
        <source>password</source>
        <translation>密码</translation>
    </message>
    <message>
        <source>home directory</source>
        <translation>用户目录</translation>
    </message>
    <message>
        <source>shell</source>
        <translation>shell</translation>
    </message>
    <message>
        <source>icon</source>
        <translation>头像</translation>
    </message>
    <message>
        <source>Failed to set user attributes</source>
        <translation>设置用户属性失败</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="147"/>
        <source> update password failed</source>
        <translation>更新密码失败</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="173"/>
        <source>icon file</source>
        <translation>头像</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="184"/>
        <source>userName type</source>
        <translation>用户名</translation>
    </message>
    <message>
        <source>account type</source>
        <translation>账户类型</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="195"/>
        <source>locked</source>
        <translation>启用状态</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="203"/>
        <source>Failed to update user properties,%1</source>
        <translation>更新用户属性失败，%1</translation>
    </message>
    <message>
        <source>Failed to update user properties(%1)</source>
        <translation>更新用户属性失败(%1)</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="226"/>
        <source>Failed to delete user,%1</source>
        <translation>删除用户失败，%1</translation>
    </message>
    <message>
        <source>Failed to delete user</source>
        <translation>删除用户失败</translation>
    </message>
</context>
<context>
    <name>KiranAccountManager</name>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="94"/>
        <location filename="../src/kiran-account-manager.cpp" line="403"/>
        <source>disable</source>
        <translation>禁用</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="94"/>
        <location filename="../src/kiran-account-manager.cpp" line="403"/>
        <source>enable</source>
        <translation>启用</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="218"/>
        <source>Create new user</source>
        <translation>创建新用户</translation>
    </message>
    <message>
        <source>User Manager</source>
        <translation>账户管理工具</translation>
    </message>
    <message>
        <source>Create new account</source>
        <translation>创建新用户</translation>
    </message>
</context>
<context>
    <name>KiranAvatarEditor</name>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="40"/>
        <source>Avatar Editor</source>
        <translation>头像编辑器</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="87"/>
        <source>Confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="108"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
</context>
<context>
    <name>KiranTips</name>
    <message>
        <location filename="../src/widgets/kiran-tips.ui" line="29"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_kiran-tips.h" line="71"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_kiran-tips.h" line="71"/>
        <source>Form</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>PasswordExpirationPolicyPage</name>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="247"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="247"/>
        <source>PasswordExpirationPolicyPage</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="43"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="248"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="248"/>
        <source>User expires</source>
        <translation>用户过期时间</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="67"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="249"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="249"/>
        <source>yyyy-MM-dd</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="84"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="250"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="250"/>
        <source>Last password change</source>
        <translation>最近一次密码修改时间</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="108"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="251"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="251"/>
        <source>1990-01-01</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="125"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="252"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="252"/>
        <source>Maximum vaild days of password</source>
        <translation>密码最大有限天数</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="162"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="253"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="253"/>
        <source>Prompt time before password expiration</source>
        <translation>密码过期之前提醒的天数</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="199"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="254"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="254"/>
        <source>how many days after password expires will become inactive</source>
        <translation>密码过期多少天认定为失效</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="277"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="255"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="255"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="318"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="256"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_password-expiration-policy-page.h" line="256"/>
        <source>return</source>
        <translation>返回</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="66"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="73"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="81"/>
        <source>day</source>
        <translation>日</translation>
    </message>
</context>
<context>
    <name>SelectAvatarPage</name>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="147"/>
        <source>Confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="161"/>
        <source>Return</source>
        <translation>返回</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="174"/>
        <source>select picture</source>
        <translation>选择图片</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="176"/>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation>图片文件(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</translation>
    </message>
</context>
<context>
    <name>UserInfoPage</name>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="520"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="520"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="157"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="521"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="521"/>
        <source>Account</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="203"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="522"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="522"/>
        <source>Change password</source>
        <translation>修改密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="462"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="527"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="527"/>
        <source>Password expiration policy</source>
        <translation>密码过期策略</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="233"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="523"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="523"/>
        <source>User id</source>
        <translation>用户ID</translation>
    </message>
    <message>
        <source>Account type</source>
        <translation>账户类型</translation>
    </message>
    <message>
        <source>Account status</source>
        <translation>启用账户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="292"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="524"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="524"/>
        <source>User type</source>
        <translation>用户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="354"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="525"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="525"/>
        <source>User status</source>
        <translation>启用用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="416"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="526"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="526"/>
        <source>auth manager</source>
        <translation>认证管理</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="523"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="528"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="528"/>
        <source>Confirm</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="564"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="529"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="529"/>
        <source>Delete</source>
        <translation>删除用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="623"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="530"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="530"/>
        <source>Current password</source>
        <translation>当前密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="684"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="531"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="531"/>
        <source>New password</source>
        <translation>新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="733"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="532"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="532"/>
        <source>Enter the new password again</source>
        <translation>再次输入新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="826"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="533"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="533"/>
        <source>Save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="867"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="534"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="534"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="136"/>
        <source>standard</source>
        <translation>普通用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="137"/>
        <source>administrator</source>
        <translation>管理员</translation>
    </message>
    <message>
        <source>Account information updated successfully</source>
        <translation>账户信息更新成功</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="314"/>
        <source>Password updated successfully</source>
        <translation>密码更新成功</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="320"/>
        <source>The directory and files under the user&apos;s home directory are deleted with the user.Are you sure you want to delete the user(%1)?</source>
        <translation>用户目录下的目录和文件会随用户一起删除，确定要删除%1用户吗？</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="323"/>
        <source>Warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="205"/>
        <source>Please enter the new user password</source>
        <translation>请输入新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="213"/>
        <source>Please enter the password again</source>
        <translation>请再次输入密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="219"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>两次密码不相同，请核对后，再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="230"/>
        <source>Please enter the current user password</source>
        <translation>请输入当前密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="236"/>
        <source>The current password is incorrect</source>
        <translation>当前密码错误，请再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="243"/>
        <source>The new password cannot be the same as the current password</source>
        <translation>新密码不能和旧密码相同，请重新输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="252"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="289"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="308"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="342"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="252"/>
        <source>Password encryption failed</source>
        <translation>密码加密失败</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="294"/>
        <source>user information updated successfully</source>
        <translation>用户信息更新成功</translation>
    </message>
</context>
</TS>
