<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>AccountItemWidget</name>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_account-itemwidget.h" line="83"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_account-itemwidget.h" line="83"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="63"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_account-itemwidget.h" line="84"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_account-itemwidget.h" line="84"/>
        <source>Tom Hardy</source>
        <translation></translation>
    </message>
    <message>
        <source>Create new account</source>
        <translation type="obsolete">创建新用户</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="17"/>
        <source>Create new user</source>
        <translation>创建新用户</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="89"/>
        <source>disable</source>
        <translation>禁用</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="93"/>
        <source>enable</source>
        <translation>启用</translation>
    </message>
</context>
<context>
    <name>AdvanceSettings</name>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="97"/>
        <source>Advance Settings</source>
        <translation>高级设置</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="203"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="203"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="43"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="204"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="204"/>
        <source>Login shell</source>
        <translation>登录Shell</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="89"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="205"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="205"/>
        <source>Specify user id</source>
        <translation>指定用户ID</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="262"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="207"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="207"/>
        <source>confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="303"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="208"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="208"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="114"/>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="124"/>
        <source>Automatically generated by system</source>
        <translation>由系统自动生成</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="159"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="206"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_advance-settings.h" line="206"/>
        <source>Specify user home</source>
        <translation>指定用户目录</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="156"/>
        <source>Please enter the correct path</source>
        <translation>请输入正确的路径</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="164"/>
        <source>Please enter specify user Id</source>
        <translation>请输入用户ID</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="172"/>
        <source>Please enter the correct home directory</source>
        <translation>请输入正确的用户目录</translation>
    </message>
</context>
<context>
    <name>AuthManagerPage</name>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="173"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="173"/>
        <source>AuthManagerPage</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="46"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="174"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="174"/>
        <source>Fingerprint Authentication</source>
        <translation>指纹认证</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="87"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="175"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="175"/>
        <source>Face Authentication</source>
        <translation>人脸认证</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="130"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="176"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="176"/>
        <source>Password Authentication</source>
        <translation>密码认证</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="204"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="177"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="177"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="245"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="178"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_auth-manager-page.h" line="178"/>
        <source>return</source>
        <translation>返回</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="142"/>
        <source>add fingerprint</source>
        <translation>录入指纹数据</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="155"/>
        <source>add face</source>
        <translation>录入人脸数据</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="172"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="322"/>
        <source>error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="173"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="323"/>
        <source>please ensure that at least one authentication option exists</source>
        <translation>请确保至少一个认证选项打开</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="515"/>
        <source>fingerprint_</source>
        <translation>指纹_</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="515"/>
        <source>face_</source>
        <translation>人脸_</translation>
    </message>
</context>
<context>
    <name>BiometricItem</name>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="77"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="77"/>
        <source>BiometricItem</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="35"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="78"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="78"/>
        <source>text</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="73"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="79"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_biometric-item.h" line="79"/>
        <source>add</source>
        <translation>添加</translation>
    </message>
</context>
<context>
    <name>CreateUserPage</name>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="101"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="287"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="287"/>
        <source>Login name</source>
        <translation>登录名</translation>
    </message>
    <message>
        <source>Account type</source>
        <translation type="vanished">账户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="65"/>
        <source>standard</source>
        <translation>普通用户</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="66"/>
        <source>administrator</source>
        <translation>管理员</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="286"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="286"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="147"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="288"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="288"/>
        <source>User type</source>
        <translation>用户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="190"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="289"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="289"/>
        <source>Password</source>
        <translation>用户密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="239"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="290"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="290"/>
        <source>Confirm password</source>
        <translation>确认密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="294"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="291"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="291"/>
        <source>Advance setting</source>
        <translation>高级设置</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="389"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="292"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="292"/>
        <source>Confirm</source>
        <translation>创建</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="436"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="293"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_create-user-page.h" line="293"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <source>Please enter account name first</source>
        <translation type="vanished">请先输入账户名</translation>
    </message>
    <message>
        <source>Please enter your account name</source>
        <translation type="vanished">请输入账户名</translation>
    </message>
    <message>
        <source>Account cannot be a pure number</source>
        <translation type="vanished">账户名不能全为数字</translation>
    </message>
    <message>
        <source>Account already exists</source>
        <translation type="vanished">账户名已存在</translation>
    </message>
    <message>
        <source>Please enter your userName name</source>
        <translation type="vanished">请输入用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="84"/>
        <source>Please enter user name first</source>
        <translation>请输入用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="118"/>
        <source>Please enter your user name</source>
        <translation>请输入用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="134"/>
        <source>user name cannot be a pure number</source>
        <translation>用户名不能全为数字</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="141"/>
        <source>user name already exists</source>
        <translation>用户名已存在</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="153"/>
        <source>Please enter your password</source>
        <translation>请输出密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="160"/>
        <source>Please enter the password again</source>
        <translation>请再次输入密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="167"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>两次密码不相同，请核对后，再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="177"/>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="212"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="177"/>
        <source>Password encryption failed</source>
        <translation>密码加密失败</translation>
    </message>
</context>
<context>
    <name>FaceInputDialog</name>
    <message>
        <location filename="../src/pages/biometric-input-dialog/face-input-dialog/face-input-dialog.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_face-input-dialog.h" line="122"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_face-input-dialog.h" line="122"/>
        <source>FaceInputDialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/face-input-dialog/face-input-dialog.ui" line="63"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_face-input-dialog.h" line="123"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_face-input-dialog.h" line="123"/>
        <source>balabalalbala...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/face-input-dialog/face-input-dialog.ui" line="121"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_face-input-dialog.h" line="124"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_face-input-dialog.h" line="124"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/face-input-dialog/face-input-dialog.ui" line="159"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_face-input-dialog.h" line="125"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_face-input-dialog.h" line="125"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/face-input-dialog/face-input-dialog.cpp" line="59"/>
        <source>initializing face collection environment...</source>
        <translation>正在初始化人脸采集环境，请稍后</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/face-input-dialog/face-input-dialog.cpp" line="109"/>
        <source>failed to initialize face collection environment!</source>
        <translation>初始化人脸采集环境失败!</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/face-input-dialog/face-input-dialog.cpp" line="120"/>
        <location filename="../src/pages/biometric-input-dialog/face-input-dialog/face-input-dialog.cpp" line="131"/>
        <source>Failed to start collection</source>
        <translation>开始采集失败</translation>
    </message>
</context>
<context>
    <name>FingerprintInputDialog</name>
    <message>
        <location filename="../src/pages/biometric-input-dialog/fingerprint-input-dialog/fingerprint-input-dialog.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_fingerprint-input-dialog.h" line="131"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_fingerprint-input-dialog.h" line="131"/>
        <source>FingerprintInputDialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/fingerprint-input-dialog/fingerprint-input-dialog.ui" line="70"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_fingerprint-input-dialog.h" line="132"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_fingerprint-input-dialog.h" line="132"/>
        <source>balabalalbala...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/fingerprint-input-dialog/fingerprint-input-dialog.ui" line="131"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_fingerprint-input-dialog.h" line="133"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_fingerprint-input-dialog.h" line="133"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/fingerprint-input-dialog/fingerprint-input-dialog.ui" line="169"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_fingerprint-input-dialog.h" line="134"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_fingerprint-input-dialog.h" line="134"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/fingerprint-input-dialog/fingerprint-input-dialog.cpp" line="36"/>
        <source>Finger Enroll</source>
        <translation>指纹录入</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-input-dialog/fingerprint-input-dialog/fingerprint-input-dialog.cpp" line="96"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
</context>
<context>
    <name>FingerprintInputWorker</name>
    <message>
        <location filename="../src/pages/biometric-input-dialog/fingerprint-input-dialog/fingerprint-input-worker.cpp" line="66"/>
        <source>initializing fingerprint collection environment...</source>
        <translation>正在初始化指纹采集环境，请稍等</translation>
    </message>
</context>
<context>
    <name>HardWorker</name>
    <message>
        <location filename="../src/hard-worker.cpp" line="33"/>
        <source>Create User failed</source>
        <translation>创建用户失败</translation>
    </message>
    <message>
        <source>password</source>
        <translation type="vanished">密码</translation>
    </message>
    <message>
        <source>home directory</source>
        <translation type="vanished">用户目录</translation>
    </message>
    <message>
        <source>shell</source>
        <translation type="vanished">shell</translation>
    </message>
    <message>
        <source>icon</source>
        <translation type="vanished">头像</translation>
    </message>
    <message>
        <source>Failed to set user attributes</source>
        <translation type="vanished">设置用户属性失败</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="132"/>
        <source> update password failed</source>
        <translation>更新密码失败</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="158"/>
        <source>icon file</source>
        <translation>头像</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="169"/>
        <source>userName type</source>
        <translation>用户名</translation>
    </message>
    <message>
        <source>account type</source>
        <translation type="vanished">账户类型</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="180"/>
        <source>locked</source>
        <translation>启用状态</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="188"/>
        <source>Failed to update user properties,%1</source>
        <translation>更新用户属性失败，%1</translation>
    </message>
    <message>
        <source>Failed to update user properties(%1)</source>
        <translation type="vanished">更新用户属性失败(%1)</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="208"/>
        <source>Failed to delete user,%1</source>
        <translation>删除用户失败，%1</translation>
    </message>
    <message>
        <source>Failed to delete user</source>
        <translation type="vanished">删除用户失败</translation>
    </message>
</context>
<context>
    <name>KiranAccountManager</name>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="76"/>
        <location filename="../src/kiran-account-manager.cpp" line="375"/>
        <source>disable</source>
        <translation>禁用</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="76"/>
        <location filename="../src/kiran-account-manager.cpp" line="375"/>
        <source>enable</source>
        <translation>启用</translation>
    </message>
    <message>
        <source>User Manager</source>
        <translation type="vanished">账户管理工具</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="196"/>
        <source>Create new account</source>
        <translation>创建新用户</translation>
    </message>
</context>
<context>
    <name>KiranAvatarEditor</name>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="28"/>
        <source>Avatar Editor</source>
        <translation>头像编辑器</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="75"/>
        <source>Confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="96"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
</context>
<context>
    <name>KiranTips</name>
    <message>
        <location filename="../src/widgets/kiran-tips.ui" line="29"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_kiran-tips.h" line="71"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_kiran-tips.h" line="71"/>
        <source>Form</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>SelectAvatarPage</name>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="132"/>
        <source>Confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="146"/>
        <source>Return</source>
        <translation>返回</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="159"/>
        <source>select picture</source>
        <translation>选择图片</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="161"/>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation>图片文件(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</translation>
    </message>
</context>
<context>
    <name>UserInfoPage</name>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="14"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="501"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="501"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="157"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="502"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="502"/>
        <source>Account</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="203"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="503"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="503"/>
        <source>Change password</source>
        <translation>修改密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="233"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="504"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="504"/>
        <source>User id</source>
        <translation>用户ID</translation>
    </message>
    <message>
        <source>Account type</source>
        <translation type="vanished">账户类型</translation>
    </message>
    <message>
        <source>Account status</source>
        <translation type="vanished">启用账户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="292"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="505"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="505"/>
        <source>User type</source>
        <translation>用户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="354"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="506"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="506"/>
        <source>User status</source>
        <translation>启用用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="416"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="507"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="507"/>
        <source>auth manager</source>
        <translation>认证管理</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="490"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="508"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="508"/>
        <source>Confirm</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="531"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="509"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="509"/>
        <source>Delete</source>
        <translation>删除用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="590"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="510"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="510"/>
        <source>Current password</source>
        <translation>当前密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="651"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="511"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="511"/>
        <source>New password</source>
        <translation>新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="700"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="512"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="512"/>
        <source>Enter the new password again</source>
        <translation>再次输入新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="793"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="513"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="513"/>
        <source>Save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="834"/>
        <location filename="../build/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="514"/>
        <location filename="../cmake-build-debug/kiran-cpanel-account_autogen/include/ui_user-info-page.h" line="514"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="112"/>
        <source>standard</source>
        <translation>普通用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="113"/>
        <source>administrator</source>
        <translation>管理员</translation>
    </message>
    <message>
        <source>Account information updated successfully</source>
        <translation type="vanished">账户信息更新成功</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="275"/>
        <source>Password updated successfully</source>
        <translation>密码更新成功</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="281"/>
        <source>The directory and files under the user&apos;s home directory are deleted with the user.Are you sure you want to delete the user(%1)?</source>
        <translation>用户目录下的目录和文件会随用户一起删除，确定要删除%1用户吗？</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="284"/>
        <source>Warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="166"/>
        <source>Please enter the new user password</source>
        <translation>请输入新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="174"/>
        <source>Please enter the password again</source>
        <translation>请再次输入密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="180"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>两次密码不相同，请核对后，再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="191"/>
        <source>Please enter the current user password</source>
        <translation>请输入当前密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="197"/>
        <source>The current password is incorrect</source>
        <translation>当前密码错误，请再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="204"/>
        <source>The new password cannot be the same as the current password</source>
        <translation>新密码不能和旧密码相同，请重新输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="213"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="250"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="269"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="303"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="213"/>
        <source>Password encryption failed</source>
        <translation>密码加密失败</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="255"/>
        <source>user information updated successfully</source>
        <translation>用户信息更新成功</translation>
    </message>
</context>
</TS>
