/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p Appearance com.kylinsec.Kiran.SessionDaemon.Appearance.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "Appearance.h"
#include <kiran-session-daemon/appearance-i.h>

/*
 * Implementation of interface class ComKylinsecKiranSessionDaemonAppearanceInterface
 */

ComKylinsecKiranSessionDaemonAppearanceInterface::ComKylinsecKiranSessionDaemonAppearanceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComKylinsecKiranSessionDaemonAppearanceInterface *ComKylinsecKiranSessionDaemonAppearanceInterface::instance()
{
    static QMutex mutex;
    static QScopedPointer<ComKylinsecKiranSessionDaemonAppearanceInterface> pInst;

    if(Q_UNLIKELY(!pInst)){
       QMutexLocker locker(&mutex);
       if(pInst.isNull()){
           pInst.reset(new ComKylinsecKiranSessionDaemonAppearanceInterface(APPEARANCE_DBUS_NAME,
                                                                            APPEARANCE_OBJECT_PATH,
                                                                            QDBusConnection::sessionBus()));
       }
    }
    return pInst.data();
}

ComKylinsecKiranSessionDaemonAppearanceInterface::~ComKylinsecKiranSessionDaemonAppearanceInterface()
{
}

