/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.kylinsec.Kiran.SessionDaemon.Mouse.xml -p mouse-interface
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mouse-interface.h"
#include <kiran-session-daemon/mouse_i.h>

/*
 * Implementation of interface class ComKylinsecKiranSessionDaemonMouseInterface
 */

ComKylinsecKiranSessionDaemonMouseInterface::ComKylinsecKiranSessionDaemonMouseInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComKylinsecKiranSessionDaemonMouseInterface *ComKylinsecKiranSessionDaemonMouseInterface::instance()
{
    static QMutex mutex;
    static QScopedPointer<ComKylinsecKiranSessionDaemonMouseInterface> pInst;

    if(Q_UNLIKELY(!pInst)){
       QMutexLocker locker(&mutex);
       if(pInst.isNull()){
           pInst.reset(new ComKylinsecKiranSessionDaemonMouseInterface(MOUSE_DBUS_NAME,
                                                                       MOUSE_OBJECT_PATH,
                                                                       QDBusConnection::sessionBus()));
       }
    }
    return pInst.data();
}

ComKylinsecKiranSessionDaemonMouseInterface::~ComKylinsecKiranSessionDaemonMouseInterface()
{
}

