<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>AccountItemWidget</name>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="14"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="63"/>
        <source>Tom Hardy</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="36"/>
        <source>Create new user</source>
        <translation>创建新用户</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="108"/>
        <source>disable</source>
        <translation>禁用</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="112"/>
        <source>enable</source>
        <translation>启用</translation>
    </message>
</context>
<context>
    <name>AdvanceSettings</name>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="113"/>
        <source>Advance Settings</source>
        <translation>高级设置</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="14"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="43"/>
        <source>Login shell</source>
        <translation>登录Shell</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="89"/>
        <source>Specify user id</source>
        <translation>指定用户ID</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="262"/>
        <source>confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="303"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="130"/>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="140"/>
        <source>Automatically generated by system</source>
        <translation>由系统自动生成</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="159"/>
        <source>Specify user home</source>
        <translation>指定用户目录</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="171"/>
        <source>Please enter the correct path</source>
        <translation>请输入正确的路径</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="179"/>
        <source>Please enter specify user Id</source>
        <translation>请输入用户ID</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="187"/>
        <source>Please enter the correct home directory</source>
        <translation>请输入正确的用户目录</translation>
    </message>
</context>
<context>
    <name>AuthManagerPage</name>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="14"/>
        <source>AuthManagerPage</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="50"/>
        <source>Fingerprint Authentication</source>
        <translation>指纹认证</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="97"/>
        <source>Face Authentication</source>
        <translation>人脸认证</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="140"/>
        <source>Password Authentication</source>
        <translation>密码认证</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="214"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="255"/>
        <source>return</source>
        <translation>返回</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="162"/>
        <source>add fingerprint</source>
        <translation>录入指纹数据</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="175"/>
        <source>add face</source>
        <translation>录入人脸数据</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="192"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="342"/>
        <source>error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="193"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="343"/>
        <source>please ensure that at least one authentication option exists</source>
        <translation>请确保至少一个认证选项打开</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="506"/>
        <source>fingerprint_</source>
        <translation>指纹_</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="506"/>
        <source>face_</source>
        <translation>人脸_</translation>
    </message>
</context>
<context>
    <name>BiometricItem</name>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="14"/>
        <source>BiometricItem</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="35"/>
        <source>text</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="73"/>
        <source>add</source>
        <translation>添加</translation>
    </message>
</context>
<context>
    <name>CreateUserPage</name>
    <message>
        <source>Account type</source>
        <translation type="vanished">账户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="82"/>
        <source>standard</source>
        <translation>普通用户</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="83"/>
        <source>administrator</source>
        <translation>管理员</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="14"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="101"/>
        <source>User name</source>
        <translation>用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="147"/>
        <source>User type</source>
        <translation>用户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="190"/>
        <source>Password</source>
        <translation>用户密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="239"/>
        <source>Confirm password</source>
        <translation>确认密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="294"/>
        <source>Advance setting</source>
        <translation>高级设置</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="389"/>
        <source>Confirm</source>
        <translation>创建</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="436"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <source>Please enter account name first</source>
        <translation type="vanished">请先输入账户名</translation>
    </message>
    <message>
        <source>Please enter your account name</source>
        <translation type="vanished">请输入账户名</translation>
    </message>
    <message>
        <source>Account cannot be a pure number</source>
        <translation type="vanished">账户名不能全为数字</translation>
    </message>
    <message>
        <source>Account already exists</source>
        <translation type="vanished">账户名已存在</translation>
    </message>
    <message>
        <source>Please enter your userName name</source>
        <translation type="vanished">请输入用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="106"/>
        <source>Please enter user name first</source>
        <translation>请输入用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="140"/>
        <source>Please enter your user name</source>
        <translation>请输入用户名</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="156"/>
        <source>user name cannot be a pure number</source>
        <translation>用户名不能全为数字</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="163"/>
        <source>user name already exists</source>
        <translation>用户名已存在</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="175"/>
        <source>Please enter your password</source>
        <translation>请输出密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="182"/>
        <source>Please enter the password again</source>
        <translation>请再次输入密码</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="189"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>两次密码不相同，请核对后，再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="199"/>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="234"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="199"/>
        <source>Password encryption failed</source>
        <translation>密码加密失败</translation>
    </message>
</context>
<context>
    <name>DateTimeSettings</name>
    <message>
        <source>save</source>
        <translation type="obsolete">保存</translation>
    </message>
</context>
<context>
    <name>FaceEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="14"/>
        <source>FaceEnrollDialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="63"/>
        <source>balabalalbala...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="124"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="162"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="69"/>
        <source>initializing face collection environment...</source>
        <translation>正在初始化人脸采集环境，请稍后</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="119"/>
        <source>failed to initialize face collection environment!</source>
        <translation>初始化人脸采集环境失败!</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="130"/>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="141"/>
        <source>Failed to start collection</source>
        <translation>开始采集失败</translation>
    </message>
</context>
<context>
    <name>FaceInputDialog</name>
    <message>
        <source>save</source>
        <translation type="vanished">保存</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation type="vanished">取消</translation>
    </message>
    <message>
        <source>initializing face collection environment...</source>
        <translation type="vanished">正在初始化人脸采集环境，请稍后</translation>
    </message>
    <message>
        <source>failed to initialize face collection environment!</source>
        <translation type="vanished">初始化人脸采集环境失败!</translation>
    </message>
    <message>
        <source>Failed to start collection</source>
        <translation type="vanished">开始采集失败</translation>
    </message>
</context>
<context>
    <name>FingerprintEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="14"/>
        <source>FingerprintEnrollDialog</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="70"/>
        <source>balabalalbala...</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="134"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="172"/>
        <source>cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="49"/>
        <source>Finger Enroll</source>
        <translation>指纹录入</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="127"/>
        <source>This fingerprint is bound to the user(%1)</source>
        <translation>该指纹已绑定用户(%1)</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="129"/>
        <source>Info</source>
        <translation>提示</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="154"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
</context>
<context>
    <name>FingerprintInputDialog</name>
    <message>
        <source>save</source>
        <translation type="vanished">保存</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation type="vanished">取消</translation>
    </message>
    <message>
        <source>Finger Enroll</source>
        <translation type="vanished">指纹录入</translation>
    </message>
    <message>
        <source>Error</source>
        <translation type="vanished">错误</translation>
    </message>
</context>
<context>
    <name>FingerprintInputWorker</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-worker.cpp" line="78"/>
        <source>initializing fingerprint collection environment...</source>
        <translation>正在初始化指纹采集环境，请稍等</translation>
    </message>
</context>
<context>
    <name>HardWorker</name>
    <message>
        <location filename="../src/hard-worker.cpp" line="46"/>
        <source>Create User failed</source>
        <translation>创建用户失败</translation>
    </message>
    <message>
        <source>password</source>
        <translation type="vanished">密码</translation>
    </message>
    <message>
        <source>home directory</source>
        <translation type="vanished">用户目录</translation>
    </message>
    <message>
        <source>shell</source>
        <translation type="vanished">shell</translation>
    </message>
    <message>
        <source>icon</source>
        <translation type="vanished">头像</translation>
    </message>
    <message>
        <source>Failed to set user attributes</source>
        <translation type="vanished">设置用户属性失败</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="147"/>
        <source> update password failed</source>
        <translation>更新密码失败</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="173"/>
        <source>icon file</source>
        <translation>头像</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="184"/>
        <source>userName type</source>
        <translation>用户名</translation>
    </message>
    <message>
        <source>account type</source>
        <translation type="vanished">账户类型</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="195"/>
        <source>locked</source>
        <translation>启用状态</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="203"/>
        <source>Failed to update user properties,%1</source>
        <translation>更新用户属性失败，%1</translation>
    </message>
    <message>
        <source>Failed to update user properties(%1)</source>
        <translation type="vanished">更新用户属性失败(%1)</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="226"/>
        <source>Failed to delete user,%1</source>
        <translation>删除用户失败，%1</translation>
    </message>
    <message>
        <source>Failed to delete user</source>
        <translation type="vanished">删除用户失败</translation>
    </message>
</context>
<context>
    <name>KcpInterface</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">警告</translation>
    </message>
</context>
<context>
    <name>KiranAccountManager</name>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="94"/>
        <location filename="../src/kiran-account-manager.cpp" line="417"/>
        <source>disable</source>
        <translation>禁用</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="94"/>
        <location filename="../src/kiran-account-manager.cpp" line="417"/>
        <source>enable</source>
        <translation>启用</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="232"/>
        <source>Create new user</source>
        <translation>创建新用户</translation>
    </message>
    <message>
        <source>User Manager</source>
        <translation type="vanished">账户管理工具</translation>
    </message>
    <message>
        <source>Create new account</source>
        <translation type="vanished">创建新用户</translation>
    </message>
</context>
<context>
    <name>KiranAvatarEditor</name>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="40"/>
        <source>Avatar Editor</source>
        <translation>头像编辑器</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="87"/>
        <source>Confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="108"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
</context>
<context>
    <name>KiranModuleWidget</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">警告</translation>
    </message>
</context>
<context>
    <name>KiranTips</name>
    <message>
        <location filename="../src/widgets/kiran-tips.ui" line="29"/>
        <source>Form</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>LayoutPage</name>
    <message>
        <source>Return</source>
        <translation type="obsolete">返回</translation>
    </message>
</context>
<context>
    <name>PasswordExpirationPolicyPage</name>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="14"/>
        <source>PasswordExpirationPolicyPage</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="43"/>
        <source>User expires</source>
        <translation>用户过期时间</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="67"/>
        <source>yyyy-MM-dd</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="84"/>
        <source>Last password change</source>
        <translation>最近一次密码修改时间</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="108"/>
        <source>1990-01-01</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="125"/>
        <source>Maximum vaild days of password</source>
        <translation>密码最大有限天数</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="162"/>
        <source>Prompt time before password expiration</source>
        <translation>密码过期之前提醒的天数</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="199"/>
        <source>how many days after password expires will become inactive</source>
        <translation>密码过期多少天认定为失效</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="280"/>
        <source>save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="321"/>
        <source>return</source>
        <translation>返回</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="66"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="73"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="81"/>
        <source>day</source>
        <translation>日</translation>
    </message>
</context>
<context>
    <name>Popup</name>
    <message>
        <source>cancel</source>
        <translation type="obsolete">取消</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">警告</translation>
    </message>
</context>
<context>
    <name>SelectAvatarPage</name>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="147"/>
        <source>Confirm</source>
        <translation>确认</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="160"/>
        <source>Return</source>
        <translation>返回</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="173"/>
        <source>select picture</source>
        <translation>选择图片</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="175"/>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation>图片文件(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</translation>
    </message>
</context>
<context>
    <name>Shortcut</name>
    <message>
        <source>Cancel</source>
        <translation type="obsolete">取消</translation>
    </message>
    <message>
        <source>Save</source>
        <translation type="obsolete">保存</translation>
    </message>
    <message>
        <source>return</source>
        <translation type="obsolete">返回</translation>
    </message>
    <message>
        <source>Warning</source>
        <translation type="obsolete">警告</translation>
    </message>
</context>
<context>
    <name>TimezoneSettings</name>
    <message>
        <source>save</source>
        <translation type="obsolete">保存</translation>
    </message>
</context>
<context>
    <name>UserInfoPage</name>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="14"/>
        <source>Form</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="138"/>
        <source>Account</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="167"/>
        <source>Change password</source>
        <translation>修改密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="396"/>
        <source>Password expiration policy</source>
        <translation>密码过期策略</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="193"/>
        <source>User id</source>
        <translation>用户ID</translation>
    </message>
    <message>
        <source>Account type</source>
        <translation type="vanished">账户类型</translation>
    </message>
    <message>
        <source>Account status</source>
        <translation type="vanished">启用账户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="251"/>
        <source>User type</source>
        <translation>用户类型</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="312"/>
        <source>User status</source>
        <translation>启用用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="367"/>
        <source>auth manager</source>
        <translation>认证管理</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="461"/>
        <source>Confirm</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="502"/>
        <source>Delete</source>
        <translation>删除用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="577"/>
        <source>Current password</source>
        <translation>当前密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="638"/>
        <source>New password</source>
        <translation>新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="687"/>
        <source>Enter the new password again</source>
        <translation>再次输入新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="780"/>
        <source>Save</source>
        <translation>保存</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="821"/>
        <source>Cancel</source>
        <translation>取消</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="145"/>
        <source>standard</source>
        <translation>普通用户</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="146"/>
        <source>administrator</source>
        <translation>管理员</translation>
    </message>
    <message>
        <source>Account information updated successfully</source>
        <translation type="vanished">账户信息更新成功</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="330"/>
        <source>Password updated successfully</source>
        <translation>密码更新成功</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="336"/>
        <source>The directory and files under the user&apos;s home directory are deleted with the user.Are you sure you want to delete the user(%1)?</source>
        <translation>用户目录下的目录和文件会随用户一起删除，确定要删除%1用户吗？</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="339"/>
        <source>Warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="221"/>
        <source>Please enter the new user password</source>
        <translation>请输入新密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="229"/>
        <source>Please enter the password again</source>
        <translation>请再次输入密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="235"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>两次密码不相同，请核对后，再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="246"/>
        <source>Please enter the current user password</source>
        <translation>请输入当前密码</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="252"/>
        <source>The current password is incorrect</source>
        <translation>当前密码错误，请再次输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="259"/>
        <source>The new password cannot be the same as the current password</source>
        <translation>新密码不能和旧密码相同，请重新输入</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="268"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="305"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="324"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="358"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="268"/>
        <source>Password encryption failed</source>
        <translation>密码加密失败</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="310"/>
        <source>user information updated successfully</source>
        <translation>用户信息更新成功</translation>
    </message>
</context>
<context>
    <name>Wallpaper</name>
    <message>
        <source>select picture</source>
        <translation type="obsolete">选择图片</translation>
    </message>
    <message>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation type="obsolete">图片文件(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</translation>
    </message>
</context>
</TS>
