<?xml version="1.0" ?><!DOCTYPE TS><TS version="2.1" language="zh_CN">
<context>
    <name>AccountItemWidget</name>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="14"/>
        <source>Form</source>
        <translation>Маягт</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="63"/>
        <source>Tom Hardy</source>
        <translation>Том Харди</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="31"/>
        <source>Create new user</source>
        <translation>Шинэ хэрэглэгч үүсгэх</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="103"/>
        <source>disable</source>
        <translation>Хүчингүй болгох</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="107"/>
        <source>enable</source>
        <translation>Идэвхжүүлэх</translation>
    </message>
</context>
<context>
    <name>AccountSubItem</name>
    <message>
        <location filename="../src/account-subitem.cpp" line="33"/>
        <source>account</source>
        <translation>Данс</translation>
    </message>
    <message>
        <location filename="../src/account-subitem.cpp" line="59"/>
        <source>New User</source>
        <translation>Шинэ хэрэглэгчид</translation>
    </message>
</context>
<context>
    <name>AdvanceSettings</name>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="115"/>
        <source>Advance Settings</source>
        <translation>Нарийвчилсан тохиргоо</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="14"/>
        <source>Form</source>
        <translation>Маягт</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="61"/>
        <source>Login shell</source>
        <translation>Нэвтрэх бүрхүүл</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="93"/>
        <source>EditLoginShell</source>
        <translation type="unfinished">Нэвтрэх бүрхүүлийг засах</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="110"/>
        <source>Specify user id (needs to be greater than 1000)</source>
        <translation>Хэрэглэгчийн id 1000-аас их байх шаардлагатайг зааж өгнө үү</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="165"/>
        <source>EditSpecifyUserID</source>
        <translation type="unfinished">Данх</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="228"/>
        <source>EditSpecifyUserHome</source>
        <translation type="unfinished">Арьсан эсүүд</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="289"/>
        <source>ButtonConfirm</source>
        <translation type="unfinished">Товчлуурын баталгаажуулалт</translation>
    </message>
    <message>
        <source>Specify user id</source>
        <translation type="vanished">Хэрэглэгчийн id-г заана уу</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="292"/>
        <source>confirm</source>
        <translation>Баталгаажуулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="333"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">Цуцлах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="336"/>
        <source>cancel</source>
        <translation>Цуцлах</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="133"/>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="143"/>
        <source>Automatically generated by system</source>
        <translation>Системийг автоматаар үүсгэдэг</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="183"/>
        <source>Specify user home</source>
        <translation>Хэрэглэгчийн нүүр хуудсыг зааж өгөх</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="174"/>
        <source>Please enter the correct path</source>
        <translation>Зөв замыг оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="183"/>
        <source>Please enter specify user Id</source>
        <translation>Заасан хэрэглэгчийн Id-г оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="189"/>
        <source>Please enter an integer above 1000</source>
        <translation>1000-аас их бүхэл тоо оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="198"/>
        <source>Please enter the correct home directory</source>
        <translation>Зөв гэрийн директорыг оруулна уу</translation>
    </message>
</context>
<context>
    <name>AuthManagerPage</name>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="14"/>
        <source>AuthManagerPage</source>
        <translation>AuthManagerPage</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="50"/>
        <source>Fingerprint Authentication</source>
        <translation>Хурууны хээг баталгаажуулах</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="97"/>
        <source>Face Authentication</source>
        <translation>Нүүрний гэрчилгээ</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="140"/>
        <source>Password Authentication</source>
        <translation>Нууц үг баталгаажуулах</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="214"/>
        <source>ButtonSave</source>
        <translation type="unfinished">Хадгалах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="217"/>
        <source>save</source>
        <translation>Хадгалах</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="258"/>
        <source>ButtonReturn</source>
        <translation type="unfinished">Буцах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="261"/>
        <source>return</source>
        <translation>Буцах</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="160"/>
        <source>add fingerprint</source>
        <translation>Addfingerprint</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="173"/>
        <source>add face</source>
        <translation>Нүүр нэмэх</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="190"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="340"/>
        <source>error</source>
        <translation>Алдаа</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="191"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="341"/>
        <source>please ensure that at least one authentication option exists</source>
        <translation>Дор хаяж нэг гэрчлэх сонголт байгаа эсэхийг шалгана уу</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="504"/>
        <source>fingerprint_</source>
        <translation>Хурууны хээ _</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="504"/>
        <source>face_</source>
        <translation>Гоймон_</translation>
    </message>
</context>
<context>
    <name>BiometricItem</name>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="14"/>
        <source>BiometricItem</source>
        <translation>BiometricItem</translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="35"/>
        <source>text</source>
        <translation>Текст</translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="73"/>
        <source>add</source>
        <translation>Дээрээс нь</translation>
    </message>
</context>
<context>
    <name>CreateUserPage</name>
    <message>
        <source>Account type</source>
        <translation type="vanished">Дансны төрөл</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="82"/>
        <source>standard</source>
        <translation>Стандарт</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="83"/>
        <source>administrator</source>
        <translation>Админ</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="14"/>
        <source>Form</source>
        <translation>Маягт</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="74"/>
        <source>UserAvatarWidget</source>
        <translation type="unfinished">Сервер</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="104"/>
        <source>User name</source>
        <translation>Хэрэглэгчийн нэр</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="136"/>
        <source>EditUserName</source>
        <translation type="unfinished">Хэрэглэгчийн нэрийг засах</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="153"/>
        <source>User type</source>
        <translation>Хэрэглэгчийн төрөл</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="182"/>
        <source>ComboUserType</source>
        <translation type="unfinished">Хосолсон</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="199"/>
        <source>Password</source>
        <translation>Нууц үг</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="234"/>
        <source>EditPasswd</source>
        <translation type="unfinished">Мэдээлэл</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="251"/>
        <source>Confirm password</source>
        <translation>Нууц үгийг баталгаажуулах</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="286"/>
        <source>EditPasswdConfirm</source>
        <translation type="unfinished">Нууц үгийн баталгаажуулалтыг засах</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="306"/>
        <source>ButtonAdvanceSetting</source>
        <translation type="unfinished">Butona Adwanse гинж</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="312"/>
        <source>Advance setting</source>
        <translation>Урьдчилан тохируулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="407"/>
        <source>ButtonConfirm</source>
        <translation type="unfinished">Товчлуурын баталгаажуулалт</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="410"/>
        <source>Confirm</source>
        <translation>Баталгаажуулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="457"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">Цуцлах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="460"/>
        <source>Cancel</source>
        <translation>Цуцлах</translation>
    </message>
    <message>
        <source>Please enter account name first</source>
        <translation type="vanished">Эхлээд дансны нэрийг оруулна уу</translation>
    </message>
    <message>
        <source>Please enter your account name</source>
        <translation type="vanished">Өөрийн дансны нэрийг оруулна уу</translation>
    </message>
    <message>
        <source>Account cannot be a pure number</source>
        <translation type="vanished">Данс нь цэвэр тоо байж болохгүй</translation>
    </message>
    <message>
        <source>Account already exists</source>
        <translation type="vanished">Данс аль хэдийн байна</translation>
    </message>
    <message>
        <source>Please enter your userName name</source>
        <translation type="vanished">Хэрэглэгчийн нэрээ оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="106"/>
        <source>Please enter user name first</source>
        <translation>Эхлээд хэрэглэгчийн нэрээ оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="140"/>
        <source>Please enter your user name</source>
        <translation>Хэрэглэгчийн нэрээ оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="156"/>
        <source>user name cannot be a pure number</source>
        <translation>Хэрэглэгчийн нэр цэвэр тоо байж болохгүй</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="163"/>
        <source>user name already exists</source>
        <translation>Хэрэглэгчийн нэр аль хэдийн байна</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="175"/>
        <source>Please enter your password</source>
        <translation>Нууц үгээ оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="182"/>
        <source>Please enter the password again</source>
        <translation>Нууц үгээ дахин оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="189"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>Таны оруулсан нууц үг өмнөх нууц үгтэй ижил байх ёстой</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="199"/>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="234"/>
        <source>Error</source>
        <translation>Алдаа</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="199"/>
        <source>Password encryption failed</source>
        <translation>Нууц үг шифрлэлт амжилтгүй боллоо</translation>
    </message>
</context>
<context>
    <name>DateTimeSettings</name>
    <message>
        <source>save</source>
        <translation type="obsolete">Хадгалах</translation>
    </message>
</context>
<context>
    <name>FaceEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="14"/>
        <source>FaceEnrollDialog</source>
        <translation>FaceEnrollDialog</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="84"/>
        <source>EnrollProgressBar</source>
        <translation type="unfinished">EnrollProgressBar</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="99"/>
        <source>LabelEnrollTips</source>
        <translation type="unfinished">Абелнроллипс</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="102"/>
        <source>balabalalbala...</source>
        <translation>Барабарабара.Байна.Байна.</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="163"/>
        <source>ButtonSave</source>
        <translation type="unfinished">Хадгалах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="166"/>
        <source>save</source>
        <translation>Хадгалах</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="204"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">Цуцлах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="207"/>
        <source>cancel</source>
        <translation>Цуцлах</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="69"/>
        <source>initializing face collection environment...</source>
        <translation>Нүүр цуглуулах орчныг эхлүүлж байна.Байна.Байна.</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="120"/>
        <source>failed to initialize face collection environment!</source>
        <translation>Нүүр цуглуулах орчныг эхлүүлэх боломжгүй байна</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="131"/>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="142"/>
        <source>Failed to start collection</source>
        <translation>Цуглуулгыг эхлүүлэх боломжгүй байна</translation>
    </message>
</context>
<context>
    <name>FaceInputDialog</name>
    <message>
        <source>save</source>
        <translation type="vanished">Хадгалах</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation type="vanished">Цуцлах</translation>
    </message>
    <message>
        <source>initializing face collection environment...</source>
        <translation type="vanished">Нүүр цуглуулах орчныг эхлүүлж байна.Байна.Байна.</translation>
    </message>
    <message>
        <source>failed to initialize face collection environment!</source>
        <translation type="vanished">Нүүр цуглуулах орчныг эхлүүлэх боломжгүй байна</translation>
    </message>
    <message>
        <source>Failed to start collection</source>
        <translation type="vanished">Цуглуулгыг эхлүүлэх боломжгүй байна</translation>
    </message>
</context>
<context>
    <name>FingerprintEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="14"/>
        <source>FingerprintEnrollDialog</source>
        <translation>Хурууны хээ гүйлгэх харилцах цонх</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="84"/>
        <source>EnrollProgressBar</source>
        <translation type="unfinished">EnrollProgressBar</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="106"/>
        <source>EnrollTips</source>
        <translation type="unfinished">Nrollips</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="109"/>
        <source>balabalalbala...</source>
        <translation>Барабарабара.Байна.Байна.</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="173"/>
        <source>ButtonSave</source>
        <translation type="unfinished">Хадгалах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="176"/>
        <source>save</source>
        <translation>Хадгалах</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="214"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">Цуцлах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="217"/>
        <source>cancel</source>
        <translation>Цуцлах</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="49"/>
        <source>Finger Enroll</source>
        <translation>Хурууны бүртгэл</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="128"/>
        <source>This fingerprint is bound to the user(%1)</source>
        <translation>Энэ хурууны хээ% 1 хэрэглэгчтэй холбогдсон байна</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="130"/>
        <source>Info</source>
        <translation>Мэдээлэл</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="155"/>
        <source>Error</source>
        <translation>Алдаа</translation>
    </message>
</context>
<context>
    <name>FingerprintInputDialog</name>
    <message>
        <source>save</source>
        <translation type="vanished">Хадгалах</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation type="vanished">Цуцлах</translation>
    </message>
    <message>
        <source>Finger Enroll</source>
        <translation type="vanished">Хурууны бүртгэл</translation>
    </message>
    <message>
        <source>Error</source>
        <translation type="vanished">Алдаа</translation>
    </message>
</context>
<context>
    <name>FingerprintInputWorker</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-worker.cpp" line="78"/>
        <source>initializing fingerprint collection environment...</source>
        <translation>Хурууны хээ цуглуулах орчныг эхлүүлж байна.Байна.Байна.</translation>
    </message>
</context>
<context>
    <name>HardWorker</name>
    <message>
        <location filename="../src/hard-worker.cpp" line="46"/>
        <source>Create User failed</source>
        <translation>Хэрэглэгч үүсгэж чадсангүй</translation>
    </message>
    <message>
        <source>password</source>
        <translation type="vanished">Нууц үг</translation>
    </message>
    <message>
        <source>home directory</source>
        <translation type="vanished">Гэрийн лавлах</translation>
    </message>
    <message>
        <source>shell</source>
        <translation type="vanished">Бүрхүүл</translation>
    </message>
    <message>
        <source>icon</source>
        <translation type="vanished">Дүрс</translation>
    </message>
    <message>
        <source>Failed to set user attributes</source>
        <translation type="vanished">Хэрэглэгчийн шинж чанарыг тохируулах ажиллагаа амжилтгүй боллоо</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="148"/>
        <source> update password failed</source>
        <translation>Нууц үгийг шинэчлэх ажиллагаа амжилтгүй боллоо</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="175"/>
        <source>icon file</source>
        <translation>Дүрсний файл</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="186"/>
        <source>userName type</source>
        <translation>Хэрэглэгчийн нэрийн төрөл</translation>
    </message>
    <message>
        <source>account type</source>
        <translation type="vanished">Дансны төрөл</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="197"/>
        <source>locked</source>
        <translation>Түгжигдсэн</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="205"/>
        <source>Failed to update user properties,%1</source>
        <translation>Хэрэглэгчийн атрибутыг шинэчлэх ажиллагаа амжилтгүй боллоо% 1</translation>
    </message>
    <message>
        <source>Failed to update user properties(%1)</source>
        <translation type="vanished">Хэрэглэгчийн атрибут% 1-ийг шинэчлэх боломжгүй байна</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="228"/>
        <source>Failed to delete user,%1</source>
        <translation>% 1 хэрэглэгчийг устгах ажиллагаа амжилтгүй боллоо</translation>
    </message>
    <message>
        <source>Failed to delete user</source>
        <translation type="vanished">Хэрэглэгчийг устгах ажиллагаа амжилтгүй боллоо</translation>
    </message>
</context>
<context>
    <name>KcpInterface</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">Анхааруулга</translation>
    </message>
</context>
<context>
    <name>KiranAccountManager</name>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="101"/>
        <location filename="../src/kiran-account-manager.cpp" line="428"/>
        <source>disable</source>
        <translation>Хүчингүй болгох</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="101"/>
        <location filename="../src/kiran-account-manager.cpp" line="428"/>
        <source>enable</source>
        <translation>Идэвхжүүлэх</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="234"/>
        <source>Create new user</source>
        <translation>Шинэ хэрэглэгч үүсгэх</translation>
    </message>
    <message>
        <source>User Manager</source>
        <translation type="vanished">Хэрэглэгчийн менежер</translation>
    </message>
    <message>
        <source>Create new account</source>
        <translation type="vanished">Шинэ данс үүсгэх</translation>
    </message>
</context>
<context>
    <name>KiranAvatarEditor</name>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="42"/>
        <source>Avatar Editor</source>
        <translation>Аватар редактор</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="91"/>
        <source>Confirm</source>
        <translation>Баталгаажуулна уу</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="112"/>
        <source>Cancel</source>
        <translation>Цуцлах</translation>
    </message>
</context>
<context>
    <name>KiranModuleWidget</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">Анхааруулга</translation>
    </message>
</context>
<context>
    <name>LayoutPage</name>
    <message>
        <source>Return</source>
        <translation type="obsolete">Буцах</translation>
    </message>
</context>
<context>
    <name>PasswordExpirationPolicyPage</name>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="14"/>
        <source>PasswordExpirationPolicyPage</source>
        <translation>PasswordExpirationPolicyPage</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="43"/>
        <source>User expires</source>
        <translation>Хэрэглэгчийн хугацаа дууссан</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="67"/>
        <source>SpinBoxUserExpires</source>
        <translation type="unfinished">Pinoxserxpires</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="70"/>
        <source>yyyy-MM-dd</source>
        <translation>Yyyy-MM-dd</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="87"/>
        <source>Last password change</source>
        <translation>Сүүлийн нууц үг өөрчлөгдсөн</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="111"/>
        <source>LabelLastPasswdChange</source>
        <translation type="unfinished">Abelastasswdanga</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="114"/>
        <source>1990-01-01</source>
        <translation>1990-01-01</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="131"/>
        <source>Maximum vaild days of password</source>
        <translation>Нууц үгний хамгийн их хүчинтэй өдөр</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="155"/>
        <source>SpinBoxMaximumValidDays</source>
        <translation type="unfinished">SpinBoxMaximumValidDays</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="172"/>
        <source>Prompt time before password expiration</source>
        <translation>Нууц үг дуусахаас өмнө сануулах цаг</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="196"/>
        <source>SpinBoxPromptBeforeExpiration</source>
        <translation type="unfinished">SpinBoxPromptBeforeExpiration</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="213"/>
        <source>how many days after password expires will become inactive</source>
        <translation>Нууц үг дууссаны дараа хэдэн өдөр идэвхгүй болох вэ</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="237"/>
        <source>SpinBoxPasswdInactiveTime</source>
        <translation type="unfinished">SpinBoxPasswdInactiveTime</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="298"/>
        <source>ButtonSave</source>
        <translation type="unfinished">Хадгалах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="301"/>
        <source>save</source>
        <translation>Хадгалах</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="342"/>
        <source>ButtonReturn</source>
        <translation type="unfinished">Буцах товчлуур</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="345"/>
        <source>return</source>
        <translation>Буцах</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="66"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="73"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="81"/>
        <source>day</source>
        <translation>Өдөр</translation>
    </message>
</context>
<context>
    <name>Popup</name>
    <message>
        <source>cancel</source>
        <translation type="obsolete">Цуцлах</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">Анхааруулга</translation>
    </message>
</context>
<context>
    <name>SelectAvatarPage</name>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="150"/>
        <source>Confirm</source>
        <translation>Баталгаажуулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="164"/>
        <source>Return</source>
        <translation>Буцах</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="181"/>
        <source>select picture</source>
        <translation>Зургийг сонгоно уу</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="183"/>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation>Зургийн файл (*. bmp *. jpg *. png *. tif *. gif *. pcx *. tga *. exif *. fpx *. psd *. cdo *. eps *. ai *. raw *. WMF *. webp</translation>
    </message>
</context>
<context>
    <name>Shortcut</name>
    <message>
        <source>Cancel</source>
        <translation type="obsolete">Цуцлах</translation>
    </message>
    <message>
        <source>Save</source>
        <translation type="obsolete">Хадгалах</translation>
    </message>
    <message>
        <source>return</source>
        <translation type="obsolete">Буцах</translation>
    </message>
    <message>
        <source>Warning</source>
        <translation type="obsolete">Анхааруулга</translation>
    </message>
</context>
<context>
    <name>TimezoneSettings</name>
    <message>
        <source>save</source>
        <translation type="obsolete">Хадгалах</translation>
    </message>
</context>
<context>
    <name>UserInfoPage</name>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="14"/>
        <source>Form</source>
        <translation>Маягт</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="138"/>
        <source>Account</source>
        <translation>Данс</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="167"/>
        <source>Change password</source>
        <translation>Нууц үгээ солино уу</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="396"/>
        <source>Password expiration policy</source>
        <translation>Нууц үгийн хугацаа дуусах бодлого</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="193"/>
        <source>User id</source>
        <translation>Хэрэглэгчийн id</translation>
    </message>
    <message>
        <source>Account type</source>
        <translation type="vanished">Дансны төрөл</translation>
    </message>
    <message>
        <source>Account status</source>
        <translation type="vanished">Дансны байдал</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="251"/>
        <source>User type</source>
        <translation>Хэрэглэгчийн төрөл</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="312"/>
        <source>User status</source>
        <translation>Хэрэглэгчийн байдал</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="367"/>
        <source>auth manager</source>
        <translation>Гэрчлэлийн менежер</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="461"/>
        <source>Confirm</source>
        <translation>Баталгаажуулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="502"/>
        <source>Delete</source>
        <translation>Устгах</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="577"/>
        <source>Current password</source>
        <translation>Одоогийн нууц үг</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="623"/>
        <source>EditCurrentPasswd</source>
        <translation type="unfinished">Одоогийн нууц үгийг засах</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="641"/>
        <source>New password</source>
        <translation>Шинэ нууц үг</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="676"/>
        <source>EditNewPasswd</source>
        <translation type="unfinished">Шинэ нууц үгийг засах</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="693"/>
        <source>Enter the new password again</source>
        <translation>Шинэ нууц үгээ дахин оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="728"/>
        <source>EditNewPasswdAgain</source>
        <translation type="unfinished">Шинэ нууц үгээ дахин засна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="789"/>
        <source>EditPasswdSave</source>
        <translation type="unfinished">Мэдээлэл</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="792"/>
        <source>Save</source>
        <translation>Хадгалах</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="833"/>
        <source>EditPasswdCancel</source>
        <translation type="unfinished">Нууц үг засах цуцлалт</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="836"/>
        <source>Cancel</source>
        <translation>Цуцлах</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="146"/>
        <source>standard</source>
        <translation>Стандарт</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="147"/>
        <source>administrator</source>
        <translation>Админ</translation>
    </message>
    <message>
        <source>Account information updated successfully</source>
        <translation type="vanished">Дансны мэдээлэл амжилттай шинэчлэгдсэн</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="338"/>
        <source>Password updated successfully</source>
        <translation>Нууц үг амжилттай шинэчлэгдсэн</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="344"/>
        <source>The directory and files under the user's home directory are deleted with the user.Are you sure you want to delete the user(%1)?</source>
        <translation>Хэрэглэгчийн гэрийн директор дахь директор, файлууд хэрэглэгчтэй хамт устах болно Та хэрэглэгч% 1 устгахдаа итгэлтэй байна уу?</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="347"/>
        <source>Warning</source>
        <translation>Анхааруулга</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="222"/>
        <source>Please enter the new user password</source>
        <translation>Хэрэглэгчийн шинэ нууц үгийг оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="230"/>
        <source>Please enter the password again</source>
        <translation>Нууц үгээ дахин оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="236"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>Таны оруулсан нууц үг өмнөх нууц үгтэй ижил байх ёстой</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="248"/>
        <source>Please enter the current user password</source>
        <translation>Одоогийн хэрэглэгчийн нууц үгийг оруулна уу</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="254"/>
        <source>The current password is incorrect</source>
        <translation>Одоогийн нууц үг буруу байна</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="261"/>
        <source>The new password cannot be the same as the current password</source>
        <translation>Шинэ нууц үг одоогийн нууц үгтэй ижил байж болохгүй</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="267"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="275"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="313"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="332"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="366"/>
        <source>Error</source>
        <translation>Алдаа</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="267"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="275"/>
        <source>Password encryption failed</source>
        <translation>Нууц үг шифрлэлт амжилтгүй боллоо</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="318"/>
        <source>user information updated successfully</source>
        <translation>Хэрэглэгчийн мэдээлэл амжилттай шинэчлэгдсэн</translation>
    </message>
</context>
<context>
    <name>Wallpaper</name>
    <message>
        <source>select picture</source>
        <translation type="obsolete">Зургийг сонгоно уу</translation>
    </message>
    <message>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation type="obsolete">Зургийн файл (*. bmp *. jpg *. png *. tif *. gif *. pcx *. tga *. exif *. fpx *. psd *. cdo *. eps *. ai *. raw *. WMF *. webp</translation>
    </message>
</context>
</TS>