<?xml version="1.0" ?><!DOCTYPE TS><TS version="2.1" language="zh_CN">
<context>
    <name>AccountItemWidget</name>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="14"/>
        <source>Form</source>
        <translation>རྣམ་པ་</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="63"/>
        <source>Tom Hardy</source>
        <translation>ཐང་མུའུ་ཧ་ཏི།</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="31"/>
        <source>Create new user</source>
        <translation>སྤྱོད་མཁན་གསར་པ་གཏོད་པ་</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="103"/>
        <source>disable</source>
        <translation>ནུས་ཤོར་འཇུག་</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="107"/>
        <source>enable</source>
        <translation>ནུས་འཇུག་</translation>
    </message>
</context>
<context>
    <name>AccountSubItem</name>
    <message>
        <location filename="../src/account-subitem.cpp" line="33"/>
        <source>account</source>
        <translation>ཐོ་ཁོངས་</translation>
    </message>
    <message>
        <location filename="../src/account-subitem.cpp" line="59"/>
        <source>New User</source>
        <translation>སྤྱོད་མཁན་གསར་པ་</translation>
    </message>
</context>
<context>
    <name>AdvanceSettings</name>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="115"/>
        <source>Advance Settings</source>
        <translation>མཐོ་རིམ་སྒྲིག་འགོད་</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="14"/>
        <source>Form</source>
        <translation>རྣམ་པ་</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="61"/>
        <source>Login shell</source>
        <translation>ཐོ་འགོདshlel</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="93"/>
        <source>EditLoginShell</source>
        <translation type="unfinished">ཐོ་འཇུག་ཕྱི་ཤུན་རྩོམ་སྒྲིག་བྱེད།</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="110"/>
        <source>Specify user id (needs to be greater than 1000)</source>
        <translation>གཏན་འཁེལ་བྱས་པའི་སྤྱོད་མཁནid（1000ལས་མང་དགོས）</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="165"/>
        <source>EditSpecifyUserID</source>
        <translation type="unfinished">ཆུ་དེམ་</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="228"/>
        <source>EditSpecifyUserHome</source>
        <translation type="unfinished">པགས་རྒྱུའི་ཕྲ་ཕུང་</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="289"/>
        <source>ButtonConfirm</source>
        <translation type="unfinished">མཐེབ་གནོན་ངོས་འཛིན་</translation>
    </message>
    <message>
        <source>Specify user id</source>
        <translation type="vanished">དམིགས་འཛུགས་སྤྱོད་མཁན་id་</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="292"/>
        <source>confirm</source>
        <translation>ངོས་འཛིན་</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="333"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">མཐེབ་གནོན་འདོར་བ།</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="336"/>
        <source>cancel</source>
        <translation>མེད་པར་བཟོ་བ་</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="133"/>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="143"/>
        <source>Automatically generated by system</source>
        <translation>རྒྱུད་ཁོངས་རང་འགྲུབ་</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="183"/>
        <source>Specify user home</source>
        <translation>དམིགས་འཛུགས་སྤྱོད་མཁན་གཙོ་ངོས།</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="174"/>
        <source>Please enter the correct path</source>
        <translation>ཡང་དག་པའི་ཐབས་ལམ་ནང་འཇུག་རོགས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="183"/>
        <source>Please enter specify user Id</source>
        <translation>རོགས་།དམིགས་འཛུགས་སྤྱོད་མཁན་གྱི་Idནང་འཇུག་།</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="189"/>
        <source>Please enter an integer above 1000</source>
        <translation>1000ལས་ཆེ་བའི་ཧྲིལ་གྲངས་རོགས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="198"/>
        <source>Please enter the correct home directory</source>
        <translation>ཡང་དག་པའི་དཀར་ཆག་གཙོ་བོ་རོགས་།</translation>
    </message>
</context>
<context>
    <name>AuthManagerPage</name>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="14"/>
        <source>AuthManagerPage</source>
        <translation>AuthManagerPage</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="50"/>
        <source>Fingerprint Authentication</source>
        <translation>མཛུབ་རིས་དཔང་དངོས་བདེན་པ་ཡིན་པའི་ར་སྤྲོད་</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="97"/>
        <source>Face Authentication</source>
        <translation>མིའི་གདོང་གི་དཔང་དངོས་བདེན་པ་ཡིན་པའི་ར་སྤྲོད་</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="140"/>
        <source>Password Authentication</source>
        <translation>གསང་ཨང་ར་སྤྲོད་</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="214"/>
        <source>ButtonSave</source>
        <translation type="unfinished">མཐེབ་གནོན་ཉར་ཚགས་</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="217"/>
        <source>save</source>
        <translation>ཉར་ཚགས།</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="258"/>
        <source>ButtonReturn</source>
        <translation type="unfinished">མཐེབ་གནོན་ཕྱིར་ལོག</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="261"/>
        <source>return</source>
        <translation>ཕྱིར་ལོག</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="160"/>
        <source>add fingerprint</source>
        <translation>Add fingerprint</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="173"/>
        <source>add face</source>
        <translation>སྣོན་ངོས།</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="190"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="340"/>
        <source>error</source>
        <translation>ནོར་འཁྲུལ།</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="191"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="341"/>
        <source>please ensure that at least one authentication option exists</source>
        <translation>མ་མཐར་ཡང་ཐོབ་ཐང་ར་སྤྲོད་ཀྱི་འདེམས་ཚན་ཞིག་ཡོད་པ་འགན་ལེན་བྱེད་རོགས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="504"/>
        <source>fingerprint_</source>
        <translation>མཛུབ་རིས་</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="504"/>
        <source>face_</source>
        <translation>མི་རྣམས།</translation>
    </message>
</context>
<context>
    <name>BiometricItem</name>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="14"/>
        <source>BiometricItem</source>
        <translation>BiometricItem</translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="35"/>
        <source>text</source>
        <translation>ཡིག་དེབ་</translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="73"/>
        <source>add</source>
        <translation>སྣོན་པ་</translation>
    </message>
</context>
<context>
    <name>CreateUserPage</name>
    <message>
        <source>Account type</source>
        <translation type="vanished">ཐོ་ཁོངས་ཀྱི་རིགས་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="82"/>
        <source>standard</source>
        <translation>ཚད་གཞི།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="83"/>
        <source>administrator</source>
        <translation>དོ་དམ་པ་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="14"/>
        <source>Form</source>
        <translation>རྣམ་པ་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="74"/>
        <source>UserAvatarWidget</source>
        <translation type="unfinished">ཞབས་ཞུ་ཆས་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="104"/>
        <source>User name</source>
        <translation>སྤྱོད་མཁན་གྱི་མིང་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="136"/>
        <source>EditUserName</source>
        <translation type="unfinished">སྤྱོད་མཁན་གྱི་མིང་རྩོམ་སྒྲིག་བྱེད།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="153"/>
        <source>User type</source>
        <translation>སྤྱོད་མཁན་གྱི་རིགས།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="182"/>
        <source>ComboUserType</source>
        <translation type="unfinished">སྡེབ་སྒྲིག་རིགས།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="199"/>
        <source>Password</source>
        <translation>གསང་ཨང་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="234"/>
        <source>EditPasswd</source>
        <translation type="unfinished">གཞི་གྲངས།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="251"/>
        <source>Confirm password</source>
        <translation>གསང་ཨང་ངོས་འཛིན་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="286"/>
        <source>EditPasswdConfirm</source>
        <translation type="unfinished">རྩོམ་སྒྲིག་གསང་ཨང་ངོས་འཛིན་།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="306"/>
        <source>ButtonAdvanceSetting</source>
        <translation type="unfinished">པུ་ཐོ་ན་ཨ་ཏེ་ཝན་སེ་ཕྲེང་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="312"/>
        <source>Advance setting</source>
        <translation>སྔོན་ནས་བཀོད་སྒྲིག་བྱེད་པ་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="407"/>
        <source>ButtonConfirm</source>
        <translation type="unfinished">མཐེབ་གནོན་ངོས་འཛིན་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="410"/>
        <source>Confirm</source>
        <translation>ངོས་འཛིན་</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="457"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">མཐེབ་གནོན་འདོར་བ།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="460"/>
        <source>Cancel</source>
        <translation>མེད་པར་བཟོ་བ་</translation>
    </message>
    <message>
        <source>Please enter account name first</source>
        <translation type="vanished">རོགས་།སྔོན་ལ་ཐོ་ཁོངས་ཀྱི་མིང་།</translation>
    </message>
    <message>
        <source>Please enter your account name</source>
        <translation type="vanished">རོགས་།ཁྱེད་རང་གི་ཐོ་ཁོངས་མིང་།</translation>
    </message>
    <message>
        <source>Account cannot be a pure number</source>
        <translation type="vanished">ཐོ་ཁོངས་ནི་གྲངས་ཀ་ལྷད་མེད་ཡིན་མི་རུང་།</translation>
    </message>
    <message>
        <source>Account already exists</source>
        <translation type="vanished">ཐོ་ཁོངས་གནས་ཡོད་།</translation>
    </message>
    <message>
        <source>Please enter your userName name</source>
        <translation type="vanished">རོགས་།ཁྱེད་རང་གི་མིང་ནང་འཇུག་།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="106"/>
        <source>Please enter user name first</source>
        <translation>སྔོན་ལ་འཇུག་རོགས་།སྤྱོད་མཁན་གྱི་མིང་།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="140"/>
        <source>Please enter your user name</source>
        <translation>རོགས་།ཁྱེད་རང་གི་མིང་ནང་འཇུག་།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="156"/>
        <source>user name cannot be a pure number</source>
        <translation>སྤྱོད་མཁན་གྱི་མིང་ནི་གྲངས་ཀ་ཁོ་ན་ཡིན་མི་རུང་།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="163"/>
        <source>user name already exists</source>
        <translation>སྤྱོད་མཁན་གྱི་མིང་ཡོད།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="175"/>
        <source>Please enter your password</source>
        <translation>རོགས་།ཁྱེད་རང་གི་གསང་ཨང་ནང་འཇུག་།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="182"/>
        <source>Please enter the password again</source>
        <translation>ཡང་བསྐྱར་གསང་ཨང་ནང་འཇུག་རོགས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="189"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>ཁྱེད་རང་གི་གསང་ཨང་ངེས་པར་དུ་སྔོན་དང་གསང་ཨང་གཅིག་མཚུངས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="199"/>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="234"/>
        <source>Error</source>
        <translation>ནོར་འཁྲུལ།</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="199"/>
        <source>Password encryption failed</source>
        <translation>གསང་ཨང་གསང་སྡོམ་ཕམ་།</translation>
    </message>
</context>
<context>
    <name>DateTimeSettings</name>
    <message>
        <source>save</source>
        <translation type="obsolete">ཉར་ཚགས།</translation>
    </message>
</context>
<context>
    <name>FaceEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="14"/>
        <source>FaceEnrollDialog</source>
        <translation>FaceEnrollDialog</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="84"/>
        <source>EnrollProgressBar</source>
        <translation type="unfinished">EnrollessBar</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="99"/>
        <source>LabelEnrollTips</source>
        <translation type="unfinished">Abelnrollips</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="102"/>
        <source>balabalalbala...</source>
        <translation>འབའ་ལྷག་ལ་པ་ལ།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="163"/>
        <source>ButtonSave</source>
        <translation type="unfinished">མཐེབ་གནོན་ཉར་ཚགས་</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="166"/>
        <source>save</source>
        <translation>ཉར་ཚགས།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="204"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">མཐེབ་གནོན་འདོར་བ།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="207"/>
        <source>cancel</source>
        <translation>མེད་པར་བཟོ་བ་</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="69"/>
        <source>initializing face collection environment...</source>
        <translation>ཐོག་མར་མིའི་གདོང་གི་ཁོར་ཡུག་འཚོལ་བསྡུ།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="120"/>
        <source>failed to initialize face collection environment!</source>
        <translation>ཐོག་མར་མིའི་གདོང་གི་ཁོར་ཡུག་འཚོལ་བསྡུའི་ཐབས་མེད།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="131"/>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="142"/>
        <source>Failed to start collection</source>
        <translation>འཚོལ་བསྡུ་བྱེད་འགོ་འཛུགས་མི་ཐུབ་།</translation>
    </message>
</context>
<context>
    <name>FaceInputDialog</name>
    <message>
        <source>save</source>
        <translation type="vanished">ཉར་ཚགས།</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation type="vanished">མེད་པར་བཟོ་བ་</translation>
    </message>
    <message>
        <source>initializing face collection environment...</source>
        <translation type="vanished">ཐོག་མར་མིའི་གདོང་གི་ཁོར་ཡུག་འཚོལ་བསྡུ།</translation>
    </message>
    <message>
        <source>failed to initialize face collection environment!</source>
        <translation type="vanished">ཐོག་མར་མིའི་གདོང་གི་ཁོར་ཡུག་འཚོལ་བསྡུའི་ཐབས་མེད།</translation>
    </message>
    <message>
        <source>Failed to start collection</source>
        <translation type="vanished">འཚོལ་བསྡུ་བྱེད་འགོ་འཛུགས་མི་ཐུབ་།</translation>
    </message>
</context>
<context>
    <name>FingerprintEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="14"/>
        <source>FingerprintEnrollDialog</source>
        <translation>མཛུབ་རིས་འགྲིལ་གླེང་སྒྲོམ།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="84"/>
        <source>EnrollProgressBar</source>
        <translation type="unfinished">EnrollessBar</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="106"/>
        <source>EnrollTips</source>
        <translation type="unfinished">Nrollips</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="109"/>
        <source>balabalalbala...</source>
        <translation>འབའ་ལྷག་ལ་པ་ལ།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="173"/>
        <source>ButtonSave</source>
        <translation type="unfinished">མཐེབ་གནོན་ཉར་ཚགས་</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="176"/>
        <source>save</source>
        <translation>ཉར་ཚགས།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="214"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">མཐེབ་གནོན་འདོར་བ།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="217"/>
        <source>cancel</source>
        <translation>མེད་པར་བཟོ་བ་</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="49"/>
        <source>Finger Enroll</source>
        <translation>མཛུབ་མོ་ཐོ་འགོད་</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="128"/>
        <source>This fingerprint is bound to the user(%1)</source>
        <translation>མཛུབ་རིས་དེ་སྤྱོད་མཁན་ལ་སྦྱར་ཟིན།（1）</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="130"/>
        <source>Info</source>
        <translation>ཆ་འཕྲིན།</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="155"/>
        <source>Error</source>
        <translation>ནོར་འཁྲུལ།</translation>
    </message>
</context>
<context>
    <name>FingerprintInputDialog</name>
    <message>
        <source>save</source>
        <translation type="vanished">ཉར་ཚགས།</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation type="vanished">མེད་པར་བཟོ་བ་</translation>
    </message>
    <message>
        <source>Finger Enroll</source>
        <translation type="vanished">མཛུབ་མོ་ཐོ་འགོད་</translation>
    </message>
    <message>
        <source>Error</source>
        <translation type="vanished">ནོར་འཁྲུལ།</translation>
    </message>
</context>
<context>
    <name>FingerprintInputWorker</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-worker.cpp" line="78"/>
        <source>initializing fingerprint collection environment...</source>
        <translation>ཐོག་མར་ལག་རིས་འཚོལ་བསྡུའི་ཁོར་ཡུག</translation>
    </message>
</context>
<context>
    <name>HardWorker</name>
    <message>
        <location filename="../src/hard-worker.cpp" line="46"/>
        <source>Create User failed</source>
        <translation>སྤྱོད་མཁན་གསར་འཛུགས་ཕམ་པ།</translation>
    </message>
    <message>
        <source>password</source>
        <translation type="vanished">གསང་ཨང་</translation>
    </message>
    <message>
        <source>home directory</source>
        <translation type="vanished">དཀར་ཆག་གཙོ་བོ།</translation>
    </message>
    <message>
        <source>shell</source>
        <translation type="vanished">སྐོགས་ཤུན་</translation>
    </message>
    <message>
        <source>icon</source>
        <translation type="vanished">རིས་རྟགས་</translation>
    </message>
    <message>
        <source>Failed to set user attributes</source>
        <translation type="vanished">སྤྱོད་མཁན་གྱི་ངོ་བོ་འཛུགས་ཕམ་།</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="148"/>
        <source> update password failed</source>
        <translation>གསང་ཨང་གསར་སྒྱུར་ཕམ་།</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="175"/>
        <source>icon file</source>
        <translation>རིས་རྟགས་ཡིག་ཆ།</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="186"/>
        <source>userName type</source>
        <translation>སྤྱོད་མཁན་གྱི་མིང་རིགས།</translation>
    </message>
    <message>
        <source>account type</source>
        <translation type="vanished">ཐོ་ཁོངས་ཀྱི་རིགས་</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="197"/>
        <source>locked</source>
        <translation>དམིགས་འཛིན་གྱི་</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="205"/>
        <source>Failed to update user properties,%1</source>
        <translation>གསར་སྒྱུར་སྤྱོད་མཁན་གྱི་ངོ་བོ་ཕམ་དང་།1%།</translation>
    </message>
    <message>
        <source>Failed to update user properties(%1)</source>
        <translation type="vanished">སྤྱོད་མཁན་གྱི་ཁྱད་ཆོས་གསར་སྒྱུར་བྱེད་ཐབས་མེད།（1）</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="228"/>
        <source>Failed to delete user,%1</source>
        <translation>སྤྱོད་མཁན་1%བསུབ་ཕམ་།</translation>
    </message>
    <message>
        <source>Failed to delete user</source>
        <translation type="vanished">སྤྱོད་མཁན་སུབ་པ་ཕམ་</translation>
    </message>
</context>
<context>
    <name>KcpInterface</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">ཐ་ཚིག་</translation>
    </message>
</context>
<context>
    <name>KiranAccountManager</name>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="101"/>
        <location filename="../src/kiran-account-manager.cpp" line="428"/>
        <source>disable</source>
        <translation>ནུས་ཤོར་འཇུག་</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="101"/>
        <location filename="../src/kiran-account-manager.cpp" line="428"/>
        <source>enable</source>
        <translation>ནུས་འཇུག་</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="234"/>
        <source>Create new user</source>
        <translation>སྤྱོད་མཁན་གསར་པ་གཏོད་པ་</translation>
    </message>
    <message>
        <source>User Manager</source>
        <translation type="vanished">སྤྱོད་མཁན་དོ་དམ་ཆས་</translation>
    </message>
    <message>
        <source>Create new account</source>
        <translation type="vanished">ཐོ་ཁོངས་གསར་འཛུགས་</translation>
    </message>
</context>
<context>
    <name>KiranAvatarEditor</name>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="42"/>
        <source>Avatar Editor</source>
        <translation>དབུ་བརྙན་རྩོམ་སྒྲིག་ཆས་</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="91"/>
        <source>Confirm</source>
        <translation>ངོས་འཛིན་</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="112"/>
        <source>Cancel</source>
        <translation>མེད་པར་བཟོ་བ་</translation>
    </message>
</context>
<context>
    <name>KiranModuleWidget</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">ཐ་ཚིག་</translation>
    </message>
</context>
<context>
    <name>LayoutPage</name>
    <message>
        <source>Return</source>
        <translation type="obsolete">ཕྱིར་ལོག</translation>
    </message>
</context>
<context>
    <name>PasswordExpirationPolicyPage</name>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="14"/>
        <source>PasswordExpirationPolicyPage</source>
        <translation>PasaswordExper onPolicyPage</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="43"/>
        <source>User expires</source>
        <translation>སྤྱོད་མཁན་དུས་ལས་ཡོལ་བ།</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="67"/>
        <source>SpinBoxUserExpires</source>
        <translation type="unfinished">Pinoxserxper</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="70"/>
        <source>yyyy-MM-dd</source>
        <translation>yyyyy-M-dd</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="87"/>
        <source>Last password change</source>
        <translation>ཐེངས་སྔོན་མར་གསང་ཨང་བཟོ་བཅོས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="111"/>
        <source>LabelLastPasswdChange</source>
        <translation type="unfinished">Ablestaswdanga</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="114"/>
        <source>1990-01-01</source>
        <translation>1990-01-01</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="131"/>
        <source>Maximum vaild days of password</source>
        <translation>གསང་ཨང་གི་ཕན་ནུས་ཆེ་ཤོས་ཀྱི་ཉིན་གྲངས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="155"/>
        <source>SpinBoxMaximumValidDays</source>
        <translation type="unfinished">SpinBoxMaximumValidDays</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="172"/>
        <source>Prompt time before password expiration</source>
        <translation>གསང་ཨང་དུས་ཚད་མ་ཐིམ་གོང་གི་དྲན་སྐུལ་དུས་ཚོད་།</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="196"/>
        <source>SpinBoxPromptBeforeExpiration</source>
        <translation type="unfinished">SpinBoxPromptBeforeExpiomomomon</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="213"/>
        <source>how many days after password expires will become inactive</source>
        <translation>གསང་ཨང་དུས་ལས་ཡོལ་རྗེས་ཀྱི་ཉིན་ག་ཚོད་ལ་འགུལ་སྐྱོད་མིན་པའི་རྣམ་པ་ཞིག་ཏུ་འགྱུར་།</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="237"/>
        <source>SpinBoxPasswdInactiveTime</source>
        <translation type="unfinished">SpinBoxPasswdInedInacttveTime</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="298"/>
        <source>ButtonSave</source>
        <translation type="unfinished">མཐེབ་གནོན་ཉར་ཚགས་</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="301"/>
        <source>save</source>
        <translation>ཉར་ཚགས།</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="342"/>
        <source>ButtonReturn</source>
        <translation type="unfinished">མཐེབ་གནོན་ཕྱིར་ལོག</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="345"/>
        <source>return</source>
        <translation>ཕྱིར་ལོག</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="66"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="73"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="81"/>
        <source>day</source>
        <translation>ཉི་མ།</translation>
    </message>
</context>
<context>
    <name>Popup</name>
    <message>
        <source>cancel</source>
        <translation type="obsolete">མེད་པར་བཟོ་བ་</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">ཐ་ཚིག་</translation>
    </message>
</context>
<context>
    <name>SelectAvatarPage</name>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="150"/>
        <source>Confirm</source>
        <translation>ངོས་འཛིན་</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="164"/>
        <source>Return</source>
        <translation>ཕྱིར་ལོག</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="181"/>
        <source>select picture</source>
        <translation>བདམས་པར་རིས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="183"/>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation>བརྙན་རིས་ཡིག་ཆ།（༡༩。bmp.jpg.pngt.t.if.pcx.tga）</translation>
    </message>
</context>
<context>
    <name>Shortcut</name>
    <message>
        <source>Cancel</source>
        <translation type="obsolete">མེད་པར་བཟོ་བ་</translation>
    </message>
    <message>
        <source>Save</source>
        <translation type="obsolete">ཉར་ཚགས།</translation>
    </message>
    <message>
        <source>return</source>
        <translation type="obsolete">ཕྱིར་ལོག</translation>
    </message>
    <message>
        <source>Warning</source>
        <translation type="obsolete">ཐ་ཚིག་</translation>
    </message>
</context>
<context>
    <name>TimezoneSettings</name>
    <message>
        <source>save</source>
        <translation type="obsolete">ཉར་ཚགས།</translation>
    </message>
</context>
<context>
    <name>UserInfoPage</name>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="14"/>
        <source>Form</source>
        <translation>རྣམ་པ་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="138"/>
        <source>Account</source>
        <translation>ཐོ་ཁོངས་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="167"/>
        <source>Change password</source>
        <translation>གསང་ཨང་བཟོ་བཅོས་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="396"/>
        <source>Password expiration policy</source>
        <translation>གསང་ཨང་དུས་ལས་ཡོལ་བའི་ཐབས་ཇུས་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="193"/>
        <source>User id</source>
        <translation>སྤྱོད་མཁན་id་</translation>
    </message>
    <message>
        <source>Account type</source>
        <translation type="vanished">ཐོ་ཁོངས་ཀྱི་རིགས་</translation>
    </message>
    <message>
        <source>Account status</source>
        <translation type="vanished">ཐོ་ཁོངས་རྣམ་པ་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="251"/>
        <source>User type</source>
        <translation>སྤྱོད་མཁན་གྱི་རིགས།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="312"/>
        <source>User status</source>
        <translation>སྤྱོད་མཁན་གྱི་རྣམ་པ་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="367"/>
        <source>auth manager</source>
        <translation>ཐོབ་ཐང་ར་སྤྲོད་དོ་དམ་ཆས་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="461"/>
        <source>Confirm</source>
        <translation>ངོས་འཛིན་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="502"/>
        <source>Delete</source>
        <translation>སུབ་པ་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="577"/>
        <source>Current password</source>
        <translation>མིག་སྔའི་གསང་ཨང་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="623"/>
        <source>EditCurrentPasswd</source>
        <translation type="unfinished">མིག་སྔའི་གསང་ཨང་རྩོམ་སྒྲིག་བྱེད།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="641"/>
        <source>New password</source>
        <translation>གསང་ཨང་གསར་པ།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="676"/>
        <source>EditNewPasswd</source>
        <translation type="unfinished">གསང་ཨང་གསར་པ་རྩོམ་སྒྲིག་བྱེད།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="693"/>
        <source>Enter the new password again</source>
        <translation>ཡང་བསྐྱར་གསང་ཨང་གསར་པ་ནང་འཇུག་།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="728"/>
        <source>EditNewPasswdAgain</source>
        <translation type="unfinished">ཡང་བསྐྱར་གསང་ཨང་གསར་པ་རྩོམ་སྒྲིག་།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="789"/>
        <source>EditPasswdSave</source>
        <translation type="unfinished">གཞི་གྲངས།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="792"/>
        <source>Save</source>
        <translation>ཉར་ཚགས།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="833"/>
        <source>EditPasswdCancel</source>
        <translation type="unfinished">རྩོམ་སྒྲིག་པའི་གསང་གྲངས་མེད་པ་བཟོ་དགོས།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="836"/>
        <source>Cancel</source>
        <translation>མེད་པར་བཟོ་བ་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="146"/>
        <source>standard</source>
        <translation>ཚད་གཞི།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="147"/>
        <source>administrator</source>
        <translation>དོ་དམ་པ་</translation>
    </message>
    <message>
        <source>Account information updated successfully</source>
        <translation type="vanished">ཐོ་ཁོངས་ཆ་འཕྲིན་གསར་སྒྱུར་ལེགས་གྲུབ་བྱུང་།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="338"/>
        <source>Password updated successfully</source>
        <translation>གསང་ཨང་གསར་སྒྱུར་གྲུབ་འབྲས་ཐོབ་པའི་ངང་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="344"/>
        <source>The directory and files under the user's home directory are deleted with the user.Are you sure you want to delete the user(%1)?</source>
        <translation>སྤྱོད་མཁན་གྱི་དཀར་ཆག་གཙོ་བོ་འོག་གི་དཀར་ཆག་དང་ཡིག་ཆ་རྣམས་སྤྱོད་མཁན་དང་མཉམ་དུ་བསུབ་རྒྱུ་རེད། འཛད་སྤྱོད་པའི་༡%བསུབ་རྒྱུ་ཡིན་ནམ།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="347"/>
        <source>Warning</source>
        <translation>ཐ་ཚིག་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="222"/>
        <source>Please enter the new user password</source>
        <translation>རོགས་།སྤྱོད་མཁན་གསར་པ་གསང་ཨང་ནང་འཇུག་།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="230"/>
        <source>Please enter the password again</source>
        <translation>ཡང་བསྐྱར་གསང་ཨང་ནང་འཇུག་རོགས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="236"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>ཁྱེད་རང་གི་གསང་ཨང་ངེས་པར་དུ་སྔོན་དང་གསང་ཨང་གཅིག་མཚུངས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="248"/>
        <source>Please enter the current user password</source>
        <translation>མིག་སྔའི་སྤྱོད་མཁན་གྱི་གསང་ཨང་ནང་འཇུག་རོགས་།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="254"/>
        <source>The current password is incorrect</source>
        <translation>མིག་སྔའི་གསང་ཨང་ཡང་མ་དག་པ་</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="261"/>
        <source>The new password cannot be the same as the current password</source>
        <translation>གསང་ཨང་གསར་པ་དང་མིག་སྔའི་གསང་ཨང་གཅིག་མཚུངས་མི་རུང་།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="267"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="275"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="313"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="332"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="366"/>
        <source>Error</source>
        <translation>ནོར་འཁྲུལ།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="267"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="275"/>
        <source>Password encryption failed</source>
        <translation>གསང་ཨང་གསང་སྡོམ་ཕམ་།</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="318"/>
        <source>user information updated successfully</source>
        <translation>སྤྱོད་མཁན་གྱི་ཆ་འཕྲིན་གསར་སྒྱུར་གྲུབ་འབྲས་ཐོབ་པའི་ངང་།</translation>
    </message>
</context>
<context>
    <name>Wallpaper</name>
    <message>
        <source>select picture</source>
        <translation type="obsolete">བདམས་པར་རིས་།</translation>
    </message>
    <message>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation type="obsolete">བརྙན་རིས་ཡིག་ཆ།（༡༩。bmp.jpg.pngt.t.if.pcx.tga）</translation>
    </message>
</context>
</TS>