<?xml version="1.0" ?><!DOCTYPE TS><TS version="2.1" language="zh_CN">
<context>
    <name>AccountItemWidget</name>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="14"/>
        <source>Form</source>
        <translation>Пішін</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.ui" line="63"/>
        <source>Tom Hardy</source>
        <translation>Том Харди</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="31"/>
        <source>Create new user</source>
        <translation>Жаңа пайдаланушыны жасау</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="103"/>
        <source>disable</source>
        <translation>өшіру</translation>
    </message>
    <message>
        <location filename="../src/widgets/account-itemwidget.cpp" line="107"/>
        <source>enable</source>
        <translation>қосу</translation>
    </message>
</context>
<context>
    <name>AccountSubItem</name>
    <message>
        <location filename="../src/account-subitem.cpp" line="33"/>
        <source>account</source>
        <translation>аккаунт</translation>
    </message>
    <message>
        <location filename="../src/account-subitem.cpp" line="59"/>
        <source>New User</source>
        <translation>Жаңа пайдаланушы</translation>
    </message>
</context>
<context>
    <name>AdvanceSettings</name>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="115"/>
        <source>Advance Settings</source>
        <translation>Алдын ала параметрлер</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="14"/>
        <source>Form</source>
        <translation>Пішін</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="61"/>
        <source>Login shell</source>
        <translation>Кіру қабығы</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="93"/>
        <source>EditLoginShell</source>
        <translation type="unfinished">EditLoginShell</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="110"/>
        <source>Specify user id (needs to be greater than 1000)</source>
        <translation>Пайдаланушы идентификаторын көрсету (1000-нан артық болуы керек)</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="165"/>
        <source>EditSpecifyUserID</source>
        <translation type="unfinished">EditSpecifyUserID</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="228"/>
        <source>EditSpecifyUserHome</source>
        <translation type="unfinished">EditSpecifyUserHome</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="289"/>
        <source>ButtonConfirm</source>
        <translation type="unfinished">Түймешік конфирмі</translation>
    </message>
    <message>
        <source>Specify user id</source>
        <translation type="vanished">Пайдаланушы идентификатын көрсету</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="292"/>
        <source>confirm</source>
        <translation>растау</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="333"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">ТүймешігіCancel</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="336"/>
        <source>cancel</source>
        <translation>Болдырмау</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="133"/>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="143"/>
        <source>Automatically generated by system</source>
        <translation>Жүйе арқылы автоматты түрде пайда болған</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.ui" line="183"/>
        <source>Specify user home</source>
        <translation>Пайдаланушының үйін көрсету</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="174"/>
        <source>Please enter the correct path</source>
        <translation>Дұрыс жолды енгізуіңізді сұраймын</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="183"/>
        <source>Please enter specify user Id</source>
        <translation>Пайдаланушы идентификатқышын көрсетуіңізді сұраймыз</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="189"/>
        <source>Please enter an integer above 1000</source>
        <translation>1000-нан жоғары бүтін санды енгізіңіз</translation>
    </message>
    <message>
        <location filename="../src/pages/advance-settings-page/advance-settings.cpp" line="198"/>
        <source>Please enter the correct home directory</source>
        <translation>Дұрыс үй каталогын енгізуіңізді сұраймын</translation>
    </message>
</context>
<context>
    <name>AuthManagerPage</name>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="14"/>
        <source>AuthManagerPage</source>
        <translation>AuthManagerPage</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="50"/>
        <source>Fingerprint Authentication</source>
        <translation>Дактилоскопиялық аутентификация</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="97"/>
        <source>Face Authentication</source>
        <translation>Бет аутентификациясы</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="140"/>
        <source>Password Authentication</source>
        <translation>Құпия сөздің аутентификациясы</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="214"/>
        <source>ButtonSave</source>
        <translation type="unfinished">БатырмаСаңқы</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="217"/>
        <source>save</source>
        <translation>сақтау</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="258"/>
        <source>ButtonReturn</source>
        <translation type="unfinished">КнопкаРетурн</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.ui" line="261"/>
        <source>return</source>
        <translation>қайтарым</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="160"/>
        <source>add fingerprint</source>
        <translation>саусақ ізін қосу</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="173"/>
        <source>add face</source>
        <translation>бет қосу</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="190"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="340"/>
        <source>error</source>
        <translation>қате</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="191"/>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="341"/>
        <source>please ensure that at least one authentication option exists</source>
        <translation>аутентификацияның кем дегенде бір параметрі бар екенін қамтамасыз етуіңізді сұраймыз</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="504"/>
        <source>fingerprint_</source>
        <translation>fingerprint_</translation>
    </message>
    <message>
        <location filename="../src/pages/auth-manager-page/auth-manager-page.cpp" line="504"/>
        <source>face_</source>
        <translation>face_</translation>
    </message>
</context>
<context>
    <name>BiometricItem</name>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="14"/>
        <source>BiometricItem</source>
        <translation>Биометрикитем</translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="35"/>
        <source>text</source>
        <translation>мәтін</translation>
    </message>
    <message>
        <location filename="../src/widgets/biometric-item.ui" line="73"/>
        <source>add</source>
        <translation>қосу</translation>
    </message>
</context>
<context>
    <name>CreateUserPage</name>
    <message>
        <source>Account type</source>
        <translation type="vanished">Тіркелгі түрі</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="82"/>
        <source>standard</source>
        <translation>стандартты</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="83"/>
        <source>administrator</source>
        <translation>әкімші</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="14"/>
        <source>Form</source>
        <translation>Пішін</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="74"/>
        <source>UserAvatarWidget</source>
        <translation type="unfinished">UserAvatarWidget</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="104"/>
        <source>User name</source>
        <translation>Пайдаланушы аты</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="136"/>
        <source>EditUserName</source>
        <translation type="unfinished">EditUserName</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="153"/>
        <source>User type</source>
        <translation>Пайдаланушы түрі</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="182"/>
        <source>ComboUserType</source>
        <translation type="unfinished">ComboUserType</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="199"/>
        <source>Password</source>
        <translation>Пароль</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="234"/>
        <source>EditPasswd</source>
        <translation type="unfinished">EditPasswd</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="251"/>
        <source>Confirm password</source>
        <translation>Құпиясөзді растау</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="286"/>
        <source>EditPasswdConfirm</source>
        <translation type="unfinished">EditPasswdConfirm</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="306"/>
        <source>ButtonAdvanceSetting</source>
        <translation type="unfinished">ButtonAdvanceSetting</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="312"/>
        <source>Advance setting</source>
        <translation>Аванс параметрі</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="407"/>
        <source>ButtonConfirm</source>
        <translation type="unfinished">Түймешік конфирмі</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="410"/>
        <source>Confirm</source>
        <translation>Растау</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="457"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">ТүймешігіCancel</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.ui" line="460"/>
        <source>Cancel</source>
        <translation>Болдырмау</translation>
    </message>
    <message>
        <source>Please enter account name first</source>
        <translation type="vanished">Алдымен тіркелгі атауын енгізуіңізді сұраймыз</translation>
    </message>
    <message>
        <source>Please enter your account name</source>
        <translation type="vanished">Тіркелгі атауын енгізіңіз</translation>
    </message>
    <message>
        <source>Account cannot be a pure number</source>
        <translation type="vanished">Тіркелгі таза сан бола алмайды</translation>
    </message>
    <message>
        <source>Account already exists</source>
        <translation type="vanished">Тіркелгі бұрыннан бар</translation>
    </message>
    <message>
        <source>Please enter your userName name</source>
        <translation type="vanished">Пайдаланушы атыңызды енгізіңіз</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="106"/>
        <source>Please enter user name first</source>
        <translation>Алдымен пайдаланушы атын енгізуіңізді сұраймын</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="140"/>
        <source>Please enter your user name</source>
        <translation>Пайдаланушы атын енгізіңіз</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="156"/>
        <source>user name cannot be a pure number</source>
        <translation>пайдаланушы атауы таза сан бола алмайды</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="163"/>
        <source>user name already exists</source>
        <translation>пайдаланушы аты бұрыннан бар</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="175"/>
        <source>Please enter your password</source>
        <translation>Құпиясөзді енгізіңіз</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="182"/>
        <source>Please enter the password again</source>
        <translation>Құпиясөзді қайтадан енгізуіңізді сұраймын</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="189"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>Сіз енгізген құпия сөз бұрынғы сөзбен бірдей болуы керек</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="199"/>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="234"/>
        <source>Error</source>
        <translation>Қате</translation>
    </message>
    <message>
        <location filename="../src/pages/create-user-page/create-user-page.cpp" line="199"/>
        <source>Password encryption failed</source>
        <translation>Құпия сөзді шифрлау жаңылысы</translation>
    </message>
</context>
<context>
    <name>DateTimeSettings</name>
    <message>
        <source>save</source>
        <translation type="obsolete">сақтау</translation>
    </message>
</context>
<context>
    <name>FaceEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="14"/>
        <source>FaceEnrollDialog</source>
        <translation>FaceEnrollDialog</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="84"/>
        <source>EnrollProgressBar</source>
        <translation type="unfinished">ReprodprogressBar</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="99"/>
        <source>LabelEnrollTips</source>
        <translation type="unfinished">LabelEnrollTips</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="102"/>
        <source>balabalalbala...</source>
        <translation>балабалбалы...</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="163"/>
        <source>ButtonSave</source>
        <translation type="unfinished">БатырмаСаңқы</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="166"/>
        <source>save</source>
        <translation>сақтау</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="204"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">ТүймешігіCancel</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.ui" line="207"/>
        <source>cancel</source>
        <translation>Болдырмау</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="69"/>
        <source>initializing face collection environment...</source>
        <translation>бет жинау ортасын инициализациялау...</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="120"/>
        <source>failed to initialize face collection environment!</source>
        <translation>бет жинау ортасын инициаторлау мүмкін болмады!</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="131"/>
        <location filename="../src/pages/biometric-enroll-dialog/face-enroll-dialog/face-enroll-dialog.cpp" line="142"/>
        <source>Failed to start collection</source>
        <translation>Жиынды бастау жаңылысы</translation>
    </message>
</context>
<context>
    <name>FaceInputDialog</name>
    <message>
        <source>save</source>
        <translation type="vanished">сақтау</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation type="vanished">Болдырмау</translation>
    </message>
    <message>
        <source>initializing face collection environment...</source>
        <translation type="vanished">бет жинау ортасын инициализациялау...</translation>
    </message>
    <message>
        <source>failed to initialize face collection environment!</source>
        <translation type="vanished">бет жинау ортасын инициаторлау мүмкін болмады!</translation>
    </message>
    <message>
        <source>Failed to start collection</source>
        <translation type="vanished">Жиынды бастау жаңылысы</translation>
    </message>
</context>
<context>
    <name>FingerprintEnrollDialog</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="14"/>
        <source>FingerprintEnrollDialog</source>
        <translation>FingerprintEnrollDialog</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="84"/>
        <source>EnrollProgressBar</source>
        <translation type="unfinished">ReprodprogressBar</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="106"/>
        <source>EnrollTips</source>
        <translation type="unfinished">AltiptIps</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="109"/>
        <source>balabalalbala...</source>
        <translation>балабалбалы...</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="173"/>
        <source>ButtonSave</source>
        <translation type="unfinished">БатырмаСаңқы</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="176"/>
        <source>save</source>
        <translation>сақтау</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="214"/>
        <source>ButtonCancel</source>
        <translation type="unfinished">ТүймешігіCancel</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.ui" line="217"/>
        <source>cancel</source>
        <translation>Болдырмау</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="49"/>
        <source>Finger Enroll</source>
        <translation>Саусақпен оқуға қабылдау</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="128"/>
        <source>This fingerprint is bound to the user(%1)</source>
        <translation>Бұл дактилоскопия пайдаланушыға байланысты(% 1)</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="130"/>
        <source>Info</source>
        <translation>Ақпарат</translation>
    </message>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-dialog.cpp" line="155"/>
        <source>Error</source>
        <translation>Қате</translation>
    </message>
</context>
<context>
    <name>FingerprintInputDialog</name>
    <message>
        <source>save</source>
        <translation type="vanished">сақтау</translation>
    </message>
    <message>
        <source>cancel</source>
        <translation type="vanished">Болдырмау</translation>
    </message>
    <message>
        <source>Finger Enroll</source>
        <translation type="vanished">Саусақпен оқуға қабылдау</translation>
    </message>
    <message>
        <source>Error</source>
        <translation type="vanished">Қате</translation>
    </message>
</context>
<context>
    <name>FingerprintInputWorker</name>
    <message>
        <location filename="../src/pages/biometric-enroll-dialog/fingerprint-enroll-dialog/fingerprint-enroll-worker.cpp" line="78"/>
        <source>initializing fingerprint collection environment...</source>
        <translation>дактилоскопиялық жинау ортасын инициализациялау...</translation>
    </message>
</context>
<context>
    <name>HardWorker</name>
    <message>
        <location filename="../src/hard-worker.cpp" line="46"/>
        <source>Create User failed</source>
        <translation>Пайдаланушы жасау жаңылысы</translation>
    </message>
    <message>
        <source>password</source>
        <translation type="vanished">құпиясөз</translation>
    </message>
    <message>
        <source>home directory</source>
        <translation type="vanished">үй каталогы</translation>
    </message>
    <message>
        <source>shell</source>
        <translation type="vanished">қабықша</translation>
    </message>
    <message>
        <source>icon</source>
        <translation type="vanished">белгішесі</translation>
    </message>
    <message>
        <source>Failed to set user attributes</source>
        <translation type="vanished">Пайдаланушы атрибуттары орнатылмады</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="148"/>
        <source> update password failed</source>
        <translation>құпия сөзді жаңарту жаңылысы</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="175"/>
        <source>icon file</source>
        <translation>белгіше файлы</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="186"/>
        <source>userName type</source>
        <translation>пайдаланушы атының түрі</translation>
    </message>
    <message>
        <source>account type</source>
        <translation type="vanished">тіркелгі түрі</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="197"/>
        <source>locked</source>
        <translation>құлыпталған</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="205"/>
        <source>Failed to update user properties,%1</source>
        <translation>Пайдаланушы сипаттарын жаңарту жаңылысы,% 1</translation>
    </message>
    <message>
        <source>Failed to update user properties(%1)</source>
        <translation type="vanished">Пайдаланушы сипаттарын жаңарту жаңылысы(% 1)</translation>
    </message>
    <message>
        <location filename="../src/hard-worker.cpp" line="228"/>
        <source>Failed to delete user,%1</source>
        <translation>Пайдаланушыны жою жаңылысы,% 1</translation>
    </message>
    <message>
        <source>Failed to delete user</source>
        <translation type="vanished">Пайдаланушыны жою жаңылысы</translation>
    </message>
</context>
<context>
    <name>KcpInterface</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">Ескерту</translation>
    </message>
</context>
<context>
    <name>KiranAccountManager</name>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="101"/>
        <location filename="../src/kiran-account-manager.cpp" line="428"/>
        <source>disable</source>
        <translation>өшіру</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="101"/>
        <location filename="../src/kiran-account-manager.cpp" line="428"/>
        <source>enable</source>
        <translation>қосу</translation>
    </message>
    <message>
        <location filename="../src/kiran-account-manager.cpp" line="234"/>
        <source>Create new user</source>
        <translation>Жаңа пайдаланушыны жасау</translation>
    </message>
    <message>
        <source>User Manager</source>
        <translation type="vanished">Пайдаланушы менеджері</translation>
    </message>
    <message>
        <source>Create new account</source>
        <translation type="vanished">Жаңа тіркелгі жасау</translation>
    </message>
</context>
<context>
    <name>KiranAvatarEditor</name>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="42"/>
        <source>Avatar Editor</source>
        <translation>Аватар редакторы</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="91"/>
        <source>Confirm</source>
        <translation>Растау</translation>
    </message>
    <message>
        <location filename="../avatar-editor/src/kiran-avatar-editor.cpp" line="112"/>
        <source>Cancel</source>
        <translation>Болдырмау</translation>
    </message>
</context>
<context>
    <name>KiranModuleWidget</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">Ескерту</translation>
    </message>
</context>
<context>
    <name>LayoutPage</name>
    <message>
        <source>Return</source>
        <translation type="obsolete">Қайтарым</translation>
    </message>
</context>
<context>
    <name>PasswordExpirationPolicyPage</name>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="14"/>
        <source>PasswordExpirationPolicyPage</source>
        <translation>PasswordExpirationPolicyPage</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="43"/>
        <source>User expires</source>
        <translation>Пайдаланушының мерзімі бітеді</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="67"/>
        <source>SpinBoxUserExpires</source>
        <translation type="unfinished">SpinBoxUserExpires</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="70"/>
        <source>yyyy-MM-dd</source>
        <translation>Жеке тұлғаның Т.А.Ә, және қолы</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="87"/>
        <source>Last password change</source>
        <translation>Құпия сөздің соңғы өзгерісі</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="111"/>
        <source>LabelLastPasswdChange</source>
        <translation type="unfinished">LabelLastPasswdChange</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="114"/>
        <source>1990-01-01</source>
        <translation>1990-01-01</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="131"/>
        <source>Maximum vaild days of password</source>
        <translation>Парольдiң ең көп бос күндерi</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="155"/>
        <source>SpinBoxMaximumValidDays</source>
        <translation type="unfinished">SpinBoxMaximumValidDays</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="172"/>
        <source>Prompt time before password expiration</source>
        <translation>Құпия сөздің жарамдылық мерзімі аяқталғанға дейінгі жедел уақыт</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="196"/>
        <source>SpinBoxPromptBeforeExpiration</source>
        <translation type="unfinished">SpinBoxPromptBeforeExpiration</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="213"/>
        <source>how many days after password expires will become inactive</source>
        <translation>пароль мерзімі біткеннен кейін қанша күн өткен соң белсенді емес болады</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="237"/>
        <source>SpinBoxPasswdInactiveTime</source>
        <translation type="unfinished">SpinBoxPasswdInactiveTime</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="298"/>
        <source>ButtonSave</source>
        <translation type="unfinished">БатырмаСаңқы</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="301"/>
        <source>save</source>
        <translation>сақтау</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="342"/>
        <source>ButtonReturn</source>
        <translation type="unfinished">КнопкаРетурн</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.ui" line="345"/>
        <source>return</source>
        <translation>қайтарым</translation>
    </message>
    <message>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="66"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="73"/>
        <location filename="../src/pages/passwd-expiration-policy/password-expiration-policy-page.cpp" line="81"/>
        <source>day</source>
        <translation>күн</translation>
    </message>
</context>
<context>
    <name>Popup</name>
    <message>
        <source>cancel</source>
        <translation type="obsolete">Болдырмау</translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>Warning</source>
        <translation type="obsolete">Ескерту</translation>
    </message>
</context>
<context>
    <name>SelectAvatarPage</name>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="150"/>
        <source>Confirm</source>
        <translation>Растау</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="164"/>
        <source>Return</source>
        <translation>Қайтарым</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="181"/>
        <source>select picture</source>
        <translation>суретті таңдау</translation>
    </message>
    <message>
        <location filename="../src/pages/select-avatar-page/select-avatar-page.cpp" line="183"/>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation>сурет файлдары(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif*.fpx *.svg *.psd *.cdr *.cdr *.cdr *.dxf *.ufo *.eps *.ai *.raw **. WMF *.webp)</translation>
    </message>
</context>
<context>
    <name>Shortcut</name>
    <message>
        <source>Cancel</source>
        <translation type="obsolete">Болдырмау</translation>
    </message>
    <message>
        <source>Save</source>
        <translation type="obsolete">Сақтау</translation>
    </message>
    <message>
        <source>return</source>
        <translation type="obsolete">қайтарым</translation>
    </message>
    <message>
        <source>Warning</source>
        <translation type="obsolete">Ескерту</translation>
    </message>
</context>
<context>
    <name>TimezoneSettings</name>
    <message>
        <source>save</source>
        <translation type="obsolete">сақтау</translation>
    </message>
</context>
<context>
    <name>UserInfoPage</name>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="14"/>
        <source>Form</source>
        <translation>Пішін</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="138"/>
        <source>Account</source>
        <translation>Тіркелгі</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="167"/>
        <source>Change password</source>
        <translation>Құпия сөзді өзгерту</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="396"/>
        <source>Password expiration policy</source>
        <translation>Құпия сөздің жарамдылық мерзімінің аяқталу саясаты</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="193"/>
        <source>User id</source>
        <translation>Пайдаланушы идентифика- ты</translation>
    </message>
    <message>
        <source>Account type</source>
        <translation type="vanished">Тіркелгі түрі</translation>
    </message>
    <message>
        <source>Account status</source>
        <translation type="vanished">Тіркелгі күйі</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="251"/>
        <source>User type</source>
        <translation>Пайдаланушы түрі</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="312"/>
        <source>User status</source>
        <translation>Пайдаланушы күйі</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="367"/>
        <source>auth manager</source>
        <translation>auth менеджері</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="461"/>
        <source>Confirm</source>
        <translation>Растау</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="502"/>
        <source>Delete</source>
        <translation>Өшіру</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="577"/>
        <source>Current password</source>
        <translation>Назардағы құпия сөз</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="623"/>
        <source>EditCurrentPasswd</source>
        <translation type="unfinished">EditCurrentPasswd</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="641"/>
        <source>New password</source>
        <translation>Жаңа құпия сөз</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="676"/>
        <source>EditNewPasswd</source>
        <translation type="unfinished">EditNewPasswd</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="693"/>
        <source>Enter the new password again</source>
        <translation>Жаңа құпия сөзді қайтадан енгізу</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="728"/>
        <source>EditNewPasswdAgain</source>
        <translation type="unfinished">EditNewPasswdAgain</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="789"/>
        <source>EditPasswdSave</source>
        <translation type="unfinished">EditPasswdSave</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="792"/>
        <source>Save</source>
        <translation>Сақтау</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="833"/>
        <source>EditPasswdCancel</source>
        <translation type="unfinished">EditPasswdCancel</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.ui" line="836"/>
        <source>Cancel</source>
        <translation>Болдырмау</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="146"/>
        <source>standard</source>
        <translation>стандартты</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="147"/>
        <source>administrator</source>
        <translation>әкімші</translation>
    </message>
    <message>
        <source>Account information updated successfully</source>
        <translation type="vanished">Тіркелгі ақпараты сәтті жаңартылды</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="338"/>
        <source>Password updated successfully</source>
        <translation>Құпия сөз сәтті жаңартылды</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="344"/>
        <source>The directory and files under the user's home directory are deleted with the user.Are you sure you want to delete the user(%1)?</source>
        <translation>Пайдаланушының үй каталогындағы каталог пен файлдар пайдаланушымен бірге жойылады. Пайдаланушыны (% 1) жойғыңыз келетініне сенімдісіз бе?</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="347"/>
        <source>Warning</source>
        <translation>Ескерту</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="222"/>
        <source>Please enter the new user password</source>
        <translation>Жаңа пайдаланушы құпия сөзін енгізіңіз</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="230"/>
        <source>Please enter the password again</source>
        <translation>Құпиясөзді қайтадан енгізуіңізді сұраймын</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="236"/>
        <source>The password you enter must be the same as the former one</source>
        <translation>Сіз енгізген құпия сөз бұрынғы сөзбен бірдей болуы керек</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="248"/>
        <source>Please enter the current user password</source>
        <translation>Ағымдағы пайдаланушы құпия сөзін енгізіңіз</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="254"/>
        <source>The current password is incorrect</source>
        <translation>Ағымдағы пароль дұрыс емес</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="261"/>
        <source>The new password cannot be the same as the current password</source>
        <translation>Жаңа құпия сөз ағымдағы құпия сөзбен бірдей бола алмайды</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="267"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="275"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="313"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="332"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="366"/>
        <source>Error</source>
        <translation>Қате</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="267"/>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="275"/>
        <source>Password encryption failed</source>
        <translation>Құпия сөзді шифрлау жаңылысы</translation>
    </message>
    <message>
        <location filename="../src/pages/user-info-page/user-info-page.cpp" line="318"/>
        <source>user information updated successfully</source>
        <translation>пайдаланушы ақпараты сәтті жаңартылды</translation>
    </message>
</context>
<context>
    <name>Wallpaper</name>
    <message>
        <source>select picture</source>
        <translation type="obsolete">суретті таңдау</translation>
    </message>
    <message>
        <source>image files(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif *.fpx *.svg *.psd *.cdr *.pcd *.dxf *.ufo *.eps *.ai *.raw *.WMF *.webp)</source>
        <translation type="obsolete">сурет файлдары(*.bmp *.jpg *.png *.tif *.gif *.pcx *.tga *.exif*.fpx *.svg *.psd *.cdr *.cdr *.cdr *.dxf *.ufo *.eps *.ai *.raw **. WMF *.webp)</translation>
    </message>
</context>
</TS>